### ISSUE TITLE
Can the webpage HTML5 video element be loaded into AR view ?

### ISSUE THREAD

**Issue by senthil5053** [SceneView/sceneform-android#11]
I was using SceneForm SDK for the AR capabilities on my app. I've tried loading the WebView on ViewRenderable and it worked fine with no issue. I could able to load any HTTP/HTTPS webpages. However when tried to load the webpage that uses HTML5 video element in it, then I just see the black screen instead of the actual video content. BTW, audio content plays fine.

Can the HTML5 video element be loaded into AR view ? Any suggestion on how this can be achieved ?

**Comment by ThomasGorisse** [comment]
Interesting. I will have a look on your case.

I send you a collaborator access invitation.

Can you **accept it** and **drag and drop your code** here : [../tree/master/samples/shared/webviewrenderable/](../tree/master/samples/shared/webviewrenderable/)
![image](https://user-images.githubusercontent.com/6597529/110107168-d9fbc400-7daa-11eb-9030-16f978d30129.png)

**Comment by senthil5053** [comment]
Thanks @ThomasGorisse , I could not upload the entire project. However I did upload all the code using which you could reproduce this.
