### ISSUE TITLE
Snapshot dependency : Jitpack build error

### ISSUE THREAD

**Issue by ThomasGorisse** [SceneView/sceneform-android#115]
Hi,

The Jitpack dependency is not working.

There is a build error described here https://jitpack.io/com/github/ThomasGorisse/sceneform-android-sdk/-v1.18.7-g51b2e84-101/build.log

Anyone have some gradle knowledge to hep me on that?

It would be great to have the snapshot dependency back.

Thanks

**Comment by devbridie** [comment]
This is a [common problem with gradle 7.0 + jitpack](https://github.com/jitpack/jitpack.io/issues?q=is%3Aissue+gradle+7) and has something [to do with the removal of the maven plugin in 7.0+](https://docs.gradle.org/current/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin);

You'll need maven-publish instead, [apparently this is a working example](https://github.com/serivesmejia/EOCV-Sim/blob/62b2f1ab2ffc6dcb156afb7b35bdb3b44ad735df/EOCV-Sim/build.gradle#L15).

**Comment by ThomasGorisse** [comment]
Thanks a lot @devbridie 

I don't know if GitHub package can manage Snapshot versions. I have already done it and it's quite simple to publish a package from Gradle.

**Comment by ThomasGorisse** [comment]
If someone have a little time for making a PR on this...

I don't know if it should be initiated in Android Studio during push or from a GitHub Action.

The only side effect is that the user has to configure its GitHub credentials inside Gradle in order to add the GitHub package dependency (even for public repos from what I remember)

BTW, @devbridie thanks a lot for to ARCore team for the lasts versions.

I made some test on DepthPoint and InstantPlacement inside Sceneform and I have to say that the result is pretty impressive even on a white wall with not so much lights.

https://user-images.githubusercontent.com/6597529/125099728-9e666300-e0d8-11eb-99cb-559641745eb4.mp4


I also noticed some great improvements with the AugmentedImage/Plane detection/anchoring speed and precision (less repositioning in time)

**Comment by RGregat** [comment]
I have to agree to @ThomasGorisse. The new DepthPoint Trackable is just awesome. It allowed me to replace a "pseudo" depth tracking method based on a DepthImage. My own version is still good, but the DepthPoint Trackable integrates way better into the already existing Trackables. So I love it!
