### ISSUE TITLE
Unable to recognize smooth walls. (white plain wall).

### ISSUE THREAD

**Issue by ShankarKakumani** [SceneView/sceneform-android#181]
I am trying to place a 3d model on top of a wall. 

If the wall is little rough or have any other textures on it , then it is getting recognized easily.

but it takes some time to recognize it and if the wall is plain, then it doesn't recognize at all.

any solution for such situations?

**Comment by ThomasGorisse** [comment]
You will have to move to https://github.com/SceneView to access this feature
