### ISSUE TITLE
config.setFocusMode 

### ISSUE THREAD

**Issue by zygoh1986** [SceneView/sceneform-android#182]
I am trying to get my google pixel 4a rear camera to auto focus on the marker. 

I am not able to focus till i onPause and return to the app. The auto focus works perfectly well. 

May i know why didn't it auto focus when i first initiate the camera?

Thanks in advance!

**Comment by RGregat** [comment]
If possible, please attach the Video you showed me

**Comment by MarcoGoe** [comment]
I had the same issue. Try to call session.resume() in onSessionConfiguration. This works for me:

```
override fun onSessionConfiguration(session: Session?, config: Config?) {

    if (session?.isDepthModeSupported(Config.DepthMode.AUTOMATIC) == true) {
         config?.depthMode = Config.DepthMode.AUTOMATIC
     }

     config?.focusMode = Config.FocusMode.AUTO

     session?.configure(config)
     session?.resume()
}
```
In general the auto focus is not really reliable with sceneform. Somethimes you have to wait a few seconds and move your camera back and forth to get the focus on an object. Does anybody know optimizations to get a faster and more reliable focus?
