### ISSUE TITLE
Disable shadows for nodes/models

### ISSUE THREAD

**Issue by PepaZapletal** [SceneView/sceneform-android#189]
Hi, 

how can I disable all shadows for objects/nodes? Is it possible?

I tried:
```
viewRenderable.setShadowCaster(false);
viewRenderable.setShadowReceiver(false);
```

but it's not working for me.

Thank you for the info.

**Comment by MukeshBlippar** [comment]
How to disable shadow for individual node ? I want to disable shadow for few nodes only. When I set plane renderer true then it enables shadow for all the nodes in the scene.

`arSceneView.getPlaneRenderer().setShadowReceiver(true);`

Below code is not effective for individual nodes. 

```
renderable.setShadowReceiver(false);
renderable.setShadowCaster(false);
```
