### ISSUE TITLE
Compatibility with Cloud based solutions e.g. Azure

### ISSUE THREAD

**Issue by jmonaniat** [SceneView/sceneform-android#190]
Hello,

This more about query than bug. Is SceneformMaintained compatible with Azure Cloud Spatial Anchor? Is any of the current client solutions/apps using Azure or any other cloud based solution along with SceneformMaintained sdk/lib? If so, can you recommend sample or pointers which can refer to? Also is it possible to replace old SceneForm based solution using SceneformMaintained? Do you have any migration guide or sample for the reference? 

Thanks in advance.

Best
Jvm

**Comment by doranteseduardo** [comment]
Hello,
The Azure Spatial Anchors is nothing but an alternative to the Google Cloud Anchors API.

It must work, yes.
Remember that the CloudSpatialAnchorSession is a wrapper for Arcore Session, same with CloudSpatialAnchor.
