### ISSUE TITLE
How to place a model straight on wall.

### ISSUE THREAD

**Issue by ShankarKakumani** [SceneView/sceneform-android#195]
I am working on an app, where I can place images on walls. 
( images in ImageView - I used ViewRenderable ).

now when I place it on the wall, it always gets rotated sideways or gets tilted from top to bottom. 
I need to place it like a poster on the wall. How can I achieve it? Please help me.

```
//to make the art visible correctly on Vertical wall
if (plane?.type == Plane.Type.VERTICAL) {
    artTransformableNode.setLookDirection(Vector3.forward())
}
```

I am using the above code it makes the view look straight on the wall. ( face towards the camera)
please check the below image. It is kind of rotated and not looking good
              
![art_on_wall](https://user-images.githubusercontent.com/35686278/139531903-c52e9304-cf55-4e0c-bea3-9707df57fd82.jpeg)

**Comment by ThomasGorisse** [comment]
You are doing it the right way.
But the AnchorNode will follow the ARCore [Plane](https://developers.google.com/ar/reference/java/com/google/ar/core/Plane) trackable position and rotation not the [Depth ](https://developers.google.com/ar/develop/java/depth/developer-guide) or [InstantPlacement](https://developers.google.com/ar/develop/java/instant-placement/developer-guide) one. Which are the suitable ones for what you are trying to achieve.

I'm sorry about this, but Depth and Instant Placement are actually only handled by [SceneView for Android](https://thomasgorisse.github.io/SceneformMaintained/sceneview/) which is a completely renew version of Sceneform.
You must click on sponsor or contribute to access it.

Depth Points using has those results:

https://user-images.githubusercontent.com/6597529/139533242-c0da6a96-619b-4748-bed9-36eec318d42a.mp4

https://user-images.githubusercontent.com/6597529/139533280-af0dbc57-1846-4e7e-84da-45482efca094.mp4

https://user-images.githubusercontent.com/6597529/139533312-e15edfd1-f156-40fa-9bfc-b4d8e25663e5.mp4

**Comment by ShankarKakumani** [comment]
Hi , 


Great work on the repository.


I want to sponsor this repository from sometime, 

I did ask my client about it.
He didn't gave me any response so far.


is it possible, you can share a sample apk,
which I will demo to my client and will ask him about the sponsor again.

you can give me apk with any 3d model, where i can place a model on vertical / horizontal planes. anything will be fine.

I just need it to convince my client to sponsor this repository.

**Comment by ShankarKakumani** [comment]
yeah sure,

but I do need depth, because we are facing lot of issues detection of walls and object placement.

And the depth is going to play major role in our application. If he sees the working of it. then, I am sure, I can get him to sponsor

or pay you the one time fee as mentioned in sponsor to finish the project.

**Comment by ThomasGorisse** [comment]
The demo comes from a private app that I don't want to share until it's released on the Play Store.

I can confirm that the DepthNode is in the #1 priorities of Sceneview for Android. I already started merging it and just have to fix some Quaternion to Euler Angle rotations displacements.
Even more since it comes in place of the actual Plane Renderer for placing an object when using the ArSceneView with the default ARCore Session Config.

**Comment by ShankarKakumani** [comment]
okay sure bro,


One last question.

let's say my client sponsors right now. will we get access to depth right now?

I know, It's not stable and work is still going on.

if not, is there any estimation about the depth. sorry to ask like this.

but my client is gonna ask me the same question.😅

**Comment by ThomasGorisse** [comment]
Everything is mostly ready. The first SceneView for Android will be realized in coming days.
![ezgif-4-3aedbd0a75b4](https://user-images.githubusercontent.com/6597529/141506430-ff5eeea1-b103-4103-854c-01f449bcb704.gif)

**Comment by ThomasGorisse** [comment]
Please move to [SceneView](https://github.com/SceneView/sceneview-android) for having access to the feature you request
