### ISSUE TITLE
How to use PBR materials as image maps in Sceneform

### ISSUE THREAD

**Issue by brady2037** [SceneView/sceneform-android#197]
#### want to  set `normalMap`,` metallicMap` and `roughnessMap` attribute of materials in code

now have a model in gltf format with a blank texture:
[![model-preview470.png](https://i.postimg.cc/1X17Ztwg/model-preview470.png)](https://postimg.cc/TLQJVTkG)

4 .png format material pictures on a part were obtained from 3DMAX,example：
[![Pbr-Map-2400.png](https://i.postimg.cc/3RWXkHCK/Pbr-Map-2400.png)](https://postimg.cc/BL9LzkVy)

I see the code for setting `baseColorMap` in the project simple：
[![code.png](https://i.postimg.cc/d0QCkKmh/code.png)](https://postimg.cc/ZWgn22Qm)

How to set `roughnessMap` and other properties

**Comment by ThomasGorisse** [comment]
Have a look in here (it's part of Reality Core which was never realized but you can modify those same parameters in Sceneform)
https://github.com/ThomasGorisse/realitycore/blob/main/realitycore/src/main/java/com/gorisse/thomas/realitycore/filament/MaterialInstance.kt#L49-L91

**Comment by ThomasGorisse** [comment]
Be sure to apply them to your RenderableInstance material not the Renderable directly cause it's not well handled in Sceneform

**Comment by brady2037** [comment]
> Make sure to apply them to your RenderableInstance material not the Renderable directly cause it's not well handled in Sceneform

Thank you very much for your help

**Comment by rabinansal** [comment]
@brady2037 Please share the updated code
