### ISSUE TITLE
Changing model doesn't work

### ISSUE THREAD

**Issue by heesos** [SceneView/sceneform-android#201]
Any ideas why when I change tiger model in sample in ar-model-viewer-java to a different model it shows only "Loading..." when I touch on the screen?
Tried same thing with the Kotlin version and it worked perfectly just by changing the model in file name string.

Thanks in advance for any help that could help me proceed with my project.

**Comment by RGregat** [comment]
I tried it as well and it worked for me. 
I changed in **MainActivity:91** of the **sample-ar-model-viewer-java** project the model from `https://storage.googleapis.com/ar-answers-in-search-models/static/Tiger/model.glb` to `https://storage.googleapis.com/ar-answers-in-search-models/static/GiantPanda/model.glb`. Did you tried it only once or multiple times? Maybe the online resource was not available when you tested it.

**Comment by heesos** [comment]
Oh yea your solution works but the problem comes up when instead of using html source I use downloaded model which I put into project files.
```
Uri.parse("models/model.glb")
```
Even though it is the same tiger model it still does not work.

I have tried Uri.fromFile as well still nothing.

**Comment by RGregat** [comment]
Do you have created the folder **models** inside of the **assets** folder? Or from where do you want to serve the model?

**Comment by heesos** [comment]
Well my **models** folder was not in **assets** folder, now it works as it should. Actually do you mind giving me a quick explanation why it is working when i put it in **assets** folder but not when it is in a different one?
Thank you very much for help.

**Comment by RGregat** [comment]
Content from the **assets** folder is included in the resulting **apk**. You don't need any permissions to access it. Different folders are not considered here. 
Two other places where you don't need any permissions is the **internal** and **external** app Storage

Internal App Storage
```
application.getContext().getFilesDir();
```

External App Storage
```
application.getContext().getExternalFilesDir(null);
```

If you want to access for example the **Downloads**-Folder its getting more complicated https://developer.android.com/about/versions/11/privacy/storage.
