### ISSUE TITLE
Switch to front camera.?

### ISSUE THREAD

**Issue by Arun1947** [SceneView/sceneform-android#208]
Is there any method to flip the Scene Form camera to primary and secondary (Front & Back)?

**Comment by RGregat** [comment]
You could take a look into the AugmentedFaces implemenation. It changes the used camera to **FRONT**

https://github.com/SceneView/sceneform-android/blob/5006b55f0fd3d983eebc52d916d5ea166a1ded0a/ux/src/main/java/com/google/ar/sceneform/ux/ArFrontFacingFragment.java#L24

**Comment by Arun1947** [comment]
Hi, @RGregat 
This code worked and succesfully switched to front_camera, but can't go back to back_camera while applying
filter.setFacingDirection(CameraConfig.FacingDirection.BACK); 

gives an exception -- com.google.ar.core.exceptions.UnavailableException sceneform (Failed to create AR session)

**Comment by ThomasGorisse** [comment]
You canot change the Camera settings while the Session is active.
You will have to recreate it in order to do the change.

**Comment by Arun1947** [comment]
No, The session was not active, at the initial time i added camera as Front-facing

![image](https://user-images.githubusercontent.com/94825638/143032331-edf5ef6e-6b75-4d3f-b5a4-8f52f88e0945.png)

**Comment by ThomasGorisse** [comment]
@fvito @grassydragon @doranteseduardo Does the AugmentedFace could work on the back Camera?

**Comment by doranteseduardo** [comment]
No, according to the ARCore docs:


"Augmented Faces supports front-facing (selfie) camera only...".

**Comment by Arun1947** [comment]
@doranteseduardo @ThomasGorisse Does the Augmented-features (other than AugmentedFace) could work on the front Camera?

**Comment by ThomasGorisse** [comment]
Never tried it but you can have a test and tell us here.

**Comment by doranteseduardo** [comment]
> @doranteseduardo @ThomasGorisse Does the Augmented-features (other than AugmentedFace) could work on the front Camera?

No, when the selfie camera is used only augmented faces feature work, also, the image gets mirrored, hitTest returns an empty array, no planes are detected and so-on.

When using the rear camera, all other features work except for the augmented faces.
