### ISSUE TITLE
camera delay on sample-augmented-faces project (Performance issue)

### ISSUE THREAD

**Issue by dulyabaVolpis** [SceneView/sceneform-android#218]
I've build 'sample-augmented-faces' project and noticed that it has some camera delay.
This delay is present on every device that I have (even the new ones), and some of them have bigger delay then others (for example Samsung devices)
It works fine if I comment out this line: "config.setAugmentedFaceMode(Config.AugmentedFaceMode.MESH3D)", but then I'm unable to use augmented faces feature.

Is it a known issue of this library? Do you have any advices on how to fix this issue?

**Comment by egorix** [comment]
Hey guys, I am having the same issue. Anyone got any idea why? On Samsung S10 and S20 there's a delay of around 0.5 seconds! While on Samsung S8 - there's none.
Very fishy issue it is!

**Comment by ThomasGorisse** [comment]
Hi,
Could you please try to clone the ARCore sample: https://github.com/google-ar/arcore-android-sdk/tree/master/samples%2Faugmented_faces_java
And run it with with ARCore 1.27.0 and 1.28.0 ?

**Comment by ThomasGorisse** [comment]
@devbridie Does it remind you something on the 1.27.0?

**Comment by devbridie** [comment]
Not aware of any performance issue with this setup; please let me know if this occurs in `augmented_faces_java` on the latest SDK.

**Comment by dulyabaVolpis** [comment]
@ThomasGorisse @devbridie have you noticed a delay that I'm talking about on the video in previous message ?
Do you know how it can be fixed ?

**Comment by ThomasGorisse** [comment]
I created an issue directly on the ARCore repo: https://github.com/google-ar/arcore-android-sdk/issues/1326
@dulyabaVolpis Did you also tried the 1.27.0?

**Comment by dulyabaVolpis** [comment]
@ThomasGorisse yes, I've tried it.
seems like 1.27.0 is a little bit slower
