### ISSUE TITLE
Impossible to place a layout (image, text...) over a SceneView ?

### ISSUE THREAD

**Issue by agGitHub** [SceneView/sceneform-android#221]
Hi,

I don't manage to place items over a SceneView. For example, impossible to place an ImageView or TextView or any RelativeLayout/LinearLayout.

For example, try with this layout of the demo project:
https://github.com/SceneView/sceneform-android/blob/master/samples/3d-model-viewer/src/main/res/layout/activity_main.xml

Move the following code:

```
 <ImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:src="@drawable/ic_launcher" />
```

at the bottom of the xml so that it should be visible over the SceneView.

Unfortunately, it is not the case. Only the SceneView is visible.

It seems to be a bug. Any fix or turnaround?

Thanks for your help.

**Comment by devbridie** [comment]
The sample you're showing uses `setTransparent` which sets `setZOrderOnTop`; this disables other views from being able to draw over this surface view. See https://github.com/SceneView/sceneform-android/blob/ba2c818151b91296f048711f494e1acc239ff809/core/src/main/java/com/google/ar/sceneform/SceneView.java#L146.

**Comment by agGitHub** [comment]
You saved me. I don't understand why there is this setZOrderOnTop set to true in this method... Thanks!
