### ISSUE TITLE
.glb models mostly has no textures rendered on the scene

### ISSUE THREAD

**Issue by skustra** [SceneView/sceneform-android#222]
Im using:
`implementation("com.gorisse.thomas.sceneform:sceneform:1.20.2")`

building .glb model:

```
: CompletableFuture<ModelRenderable>? {
        return ModelRenderable.builder()
            .setSource(
                context,
                Uri.parse(modelPath)
            )
            .setIsFilamentGltf(true)
            .setAsyncLoadEnabled(false)
            .build()
    }
```

waiting for the result:
```
getModelRenderable(
                            arFile.fileId,
                            arFile.fileExtension
                        )?.thenAccept { characterModel ->...})
```
                        
placing model on on the scene:
```
 scene.addChild(AnchorNode(hitResult?.createAnchor()).apply {
            addChild(TransformableNode(arFragment.transformationSystem).apply {
                renderable = marker.getModelRenderable()
                renderableInstance.animate(true)
                    .start()
            })
        })
```

I have the same results with dragon.glb, cube.glb, etc. Your sample working just fine.
I have no idea whats the problem is really, could You please take a look at this one? Some of the texture are visible, but rest of the not. 

Thank you!

![image](https://user-images.githubusercontent.com/83349532/144634274-e4bce869-310b-436c-a185-cbecdc1d260c.png)

The code is based on `**ar-model-viewer**`

**Comment by skustra** [comment]
Could I miss some lighting settings maybe?

**Comment by ThomasGorisse** [comment]
Can you please download [AR Environment Lights](https://play.google.com/store/apps/details?id=com.gorisse.thomas.ar.environmentlights)?

**Comment by skustra** [comment]
@ThomasGorisse 
![image](https://user-images.githubusercontent.com/83349532/144641584-ce831259-b28a-4906-ada7-6e7d4b12bdb7.png)

**Comment by skustra** [comment]
![image](https://user-images.githubusercontent.com/83349532/144641936-320bd57d-4702-476d-a50f-baf6c0f4fa70.png)

**Comment by ThomasGorisse** [comment]
Values seems normal. Please add a model to the screenshot.

**Comment by skustra** [comment]
![image](https://user-images.githubusercontent.com/83349532/144642537-73067154-a896-48ec-b667-b90fd1b5be0d.png)

**Comment by ThomasGorisse** [comment]
Ok, I think I know where your issue is coming from.
Are you using the ArSceneView directly (not the ArFragment)?

**Comment by skustra** [comment]
Fragment A with has ArFragment inside XML  FragmentContainerView with extends BaseArFragment

**Comment by skustra** [comment]
in BaseArFragment `  arSceneView = frameLayout.findViewById(R.id.sceneView);`

**Comment by skustra** [comment]
Might it be some issues with the lifecycle? I think the session config is set just fine. Light is set to `SENSOR_TYPE_LIGHT`

**Comment by skustra** [comment]
Also, the fragment is set to activity's supportFragmentManager not to childFragmentManager.

I get the fragment with:

```
arFragment =
            getNavigationActivity().supportFragmentManager.findFragmentById(R.id.customArFragment) as ArFragment
```

as child fragment manager was unable to find the fragment for some reason. Maybe there is a problem?

**Comment by skustra** [comment]
After I set the:
```

  this.arSceneView.lightEstimationConfig = LightEstimationConfig(
            Config.LightEstimationMode.DISABLED
        )
```

I'm able to see textures :D

**Comment by skustra** [comment]
![image](https://user-images.githubusercontent.com/83349532/144646634-a962d39d-ca41-4daa-a39d-25527be4983e.png)

**Comment by ThomasGorisse** [comment]
### Java:
```java
ArSceneViewKt.setLightEstimationConfig(arSceneView, LightEstimationConfig.REALISTIC);
```
### Kotlin:
```kotlin
arSceneView.lightEstimationConfig = LightEstimationConfig.REALISTIC
```

### Doc:
```kotlin
/**
 * ### ARCore light estimation configuration
 *
 * ARCore estimate lighting to provide directional light, ambient spherical harmonics,
 * and reflection cubemap estimation
 *
 * Light bounces off of surfaces differently depending on whether the surface has specular
 * (highly reflective) or diffuse (not reflective) properties.
 * For example, a metallic ball will be highly specular and reflect its environment, while
 * another ball painted a dull matte gray will be diffuse. Most real-world objects have a
 * combination of these properties — think of a scuffed-up bowling ball or a well-used credit
 * card.
 *
 * Reflective surfaces also pick up colors from the ambient environment. The coloring of an
 * object can be directly affected by the coloring of its environment. For example, a white ball
 * in a blue room will take on a bluish hue.
 *
 * The main directional light API calculates the direction and intensity of the scene's
 * main light source. This information allows virtual objects in your scene to show reasonably
 * positioned specular highlights, and to cast shadows in a direction consistent with other
 * visible real objects.
 *
 * @see LightEstimationConfig.REALISTIC
 * @see LightEstimationConfig.SPECTACULAR
 * @see LightEstimationConfig.AMBIENT_INTENSITY
 */
```

Added doc : https://github.com/SceneView/sceneform-android#environment-lights

**Comment by skustra** [comment]
```
 * @see LightEstimationConfig.REALISTIC
 * @see LightEstimationConfig.SPECTACULAR
 * @see LightEstimationConfig.AMBIENT_INTENSITY
```

On all of them, I see these black textures, only on `Config.LightEstimationMode.REALISTIC` I see them, but without the camera preview :D Anyway thanks for your help...

**Comment by skustra** [comment]
@ThomasGorisse I made a video. The first one is the default one. After that, I'm changing the light every 5 seconds :D 

It's working! Thanks for your help and for your work! 

https://user-images.githubusercontent.com/83349532/144654379-a4476baf-8a22-45aa-8088-4f5e3fc7384b.mp4

<3

**Comment by ThomasGorisse** [comment]
That's because the default value is applied on the ArFragment not BaseArFragment.

**Comment by ThomasGorisse** [comment]
Thanks for the nice Video shots.
What are you using to make it less then 10Mo?

**Comment by skustra** [comment]
> Thanks for the nice Video shots.
> 
> @skustra What tool are you using to make your screen record and to make it less then 10Mb?

I used a native Samsung s21 screen recorder than sent it to Telegram app (Telegram has optimized it I belive so)
