### ISSUE TITLE
Black texture/model bug resurfaced

### ISSUE THREAD

**Issue by xushichangdesmond** [SceneView/sceneform-android#251]
With reference to the issue described in [https://github.com/SceneView/sceneform-android/issues/46](https://github.com/SceneView/sceneform-android/issues/46),

.setAsyncLoadEnabled(false) did solve the aforementioned issue for me on 1.18.10, but the model/texture is black yet again after upgrading to sceneform 1.20.2. Seems the bug has resurfaced sometime in between these releases.

**Comment by ThomasGorisse** [comment]
Is it black only when loading?

**Comment by xushichangdesmond** [comment]
not only loading but thru-out its life; i might have some time to try to reproduce this in a sample proj later next week.
i was basically using the builder with setAsyncLoadEnabled(false) and only in thenAccepts's handler did I create the sceneform node and attach it to the scene.

**Comment by ThomasGorisse** [comment]
Try to disable light estimation

**Comment by xushichangdesmond** [comment]
proposed treatment works; thanks much Dr Gregory House

**Comment by ThomasGorisse** [comment]
Have a look here to choose the right estimation mode you need:
https://github.com/SceneView/sceneform-android#environment-lights

**Comment by ThomasGorisse** [comment]
Due to dark light estimation
