### ISSUE TITLE
Ability to run on a device not blessed by google?

### ISSUE THREAD

**Issue by denisk20** [SceneView/sceneform-android#268]
I know it's ar-core related, so sorry for posting here.
Any hint of how to make a sceneform app visible in the play store and runnable on a device not from the [official list](https://developers.google.com/ar/devices)? This list is often outdated and some exotic devices which can run sceneform fine are not included.

**Comment by ThomasGorisse** [comment]
```xml
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera.ar" android:required="true"/>

<application>
    ...
    <meta-data android:name="com.google.ar.core" android:value="required" />
</application>
```

**Comment by denisk20** [comment]
Thank you @ThomasGorisse.

> Then check for Sceneform compatibility at runtime

Is there an example of this somewhere?

**Comment by ThomasGorisse** [comment]
```kotlin
if (Sceneform.isSupported(this)) {
    //Your code
}
```

**Comment by denisk20** [comment]
Cool, will try that. Thank you!
