### ISSUE TITLE
stopIteration was called without calling startIteration when using ArSceneView.getScene().callOnHierarchy()

### ISSUE THREAD

**Issue by sarimmehdi** [SceneView/sceneform-android#271]
I encountered this error for the first time for this piece of code:

```
public List<CustomAnchorNode> getAllAnchorNodesInScene() {
        List<CustomAnchorNode> anchorNodes = new ArrayList<>();
        arSceneView.getScene().callOnHierarchy(node -> {
            String anchorName = node.getName();
            if (anchorName.startsWith(Enums.NodeNames.ANCHOR.name())) {
                anchorNodes.add((CustomAnchorNode) node);
            }
        });
        return anchorNodes;
    }
```
The error occurs for this line: `arSceneView.getScene().callOnHierarchy`

I tried to do some digging here to see if I can understand why this is happening. I came across [this](https://github.com/SceneView/sceneform-android/blob/ba2c818151b91296f048711f494e1acc239ff809/core/src/main/java/com/google/ar/sceneform/NodeParent.java#L209). What I don't understand, however, is why would `iteratingCounter` ever become negative since, according to [here](https://github.com/SceneView/sceneform-android/blob/ba2c818151b91296f048711f494e1acc239ff809/core/src/main/java/com/google/ar/sceneform/NodeParent.java#L93), startIterating() is called before stopIterating(). Am I missing something here?

Some more context, the above code for `getAllAnchorNodesInScene()` is called immediately after I get the view binding for ArSceneView in the OnCreate() function. This is because in my program I am running a background thread where I need to get the distance of my camera to all the anchors. I start this thread immediately, I guess I should start it after a pause of 1 second? I would really appreciate an expert weighing in on this and possible explaining why this error happens in the first place because this is the first time I encountered it.

**Comment by ThomasGorisse** [comment]
Some nodes like the Camera node might be added by Sceneform between onCreate and onResume so you can't really rely on `callOnHierarchy`

Why not keeping a list of your created anchor nodes on your side?

**Comment by sarimmehdi** [comment]
@ThomasGorisse that is actually a good idea. Thank you, I will do that now.
