### ISSUE TITLE
AugmentedImage & play animation with .apng format

### ISSUE THREAD

**Issue by baonq-2356** [SceneView/sceneform-android#280]
Hi everybody, i would like use augmentd image to detect my image, then play animation with .apng format (https://en.wikipedia.org/wiki/APNG).
I saw in the demo augmented image detect matrix image then play matrix video, a surface (same ratio and size with matrix image) is given to mediaPlayer
`mediaPlayer = MediaPlayer.create(this, R.raw.matrix)
                    mediaPlayer?.apply {
                        isLooping = true
                        setSurface(externalTexture.surface)
                    }
                    mediaPlayer?.start()`
now i want to set that surface into a View to play .apng animation.  How can i do it?

**Comment by RGregat** [comment]
Use a ViewRenderable instead of the VideoNode and add a Layout with an ImageView. Use a Library to load the apng and set it to the ImageView.
I found several Libraries which should work , https://github.com/penfeizhou/APNG4Android or https://github.com/line/apng-drawable

**Comment by baonq-2356** [comment]
@RGregat yeah, i understood this idea, but i still have some difficult during implement, can you reply my message in discord channel? i can show my code and clear explain for my context, pls!

**Comment by RGregat** [comment]
To give you an answer about webp. You can use webp without any Library, simple use the ImageDecoder class (https://medium.com/appnroll-publication/what-is-new-in-android-p-imagedecoder-animatedimagedrawable-a65744bec7c1). 

```Java
// Code-Snipped in Java. Load GIF or WEBP files and set them in an ImageView
ImageDecoder.Source source = ImageDecoder
   .createSource(
      context.getAssets(),
      imagePath);

Drawable drawable = ImageDecoder
   .decodeDrawable(source);

binding.imageView.setImageDrawable(drawable);

if (drawable instanceof AnimatedImageDrawable) {
   ((AnimatedImageDrawable) drawable).start();
}
```

Creation of WEBP files is possible with **ffmpeg**

```bash
ffmpeg \
-i INPUT_FILE \
-vcodec libwebp \
-preset picture \
-loop 0 \
-an -vsync 0 \
-vf "fps=10, scale=400:-1" \
-q:v 50 \
-compression_level 6 \
-ss xx:xx:xx -to xx:xx:xx \
OUTPUL_FILE
``` 

A more complete example. For the rotation and positioning you have to look by yourself. But I would appreciate it, if you can post your findings here.

```java
private CompletableFuture<ViewRenderable> viewRenderableFuture;
private Drawable drawable;
```

```java
@RequiresApi(api = Build.VERSION_CODES.P)
private void loadViewRenderable() throws IOException {
   ImageDecoder.Source source = ImageDecoder
      .createSource(
         this.getAssets(),
         "skizze.webp");

   drawable = ImageDecoder
     .decodeDrawable(source);

   View view = ((LayoutInflater) this
      .getSystemService(Service.LAYOUT_INFLATER_SERVICE))
      .inflate(R.layout.view_renderable_layout, null);
   ImageView imageView = view.findViewById(R.id.imageView);
   imageView.setImageDrawable(drawable);

   viewRenderableFuture = ViewRenderable
      .builder()
      .setView(this, view)
      .build();
}
```

```java
if (augmentedImage.getTrackingState() == TrackingState.TRACKING
   && augmentedImage.getTrackingMethod() == AugmentedImage.TrackingMethod.FULL_TRACKING) {

   // Setting anchor to the center of Augmented Image
   AnchorNode anchorNode = new AnchorNode(augmentedImage.createAnchor(augmentedImage.getCenterPose()));

   if (!matrixDetected && augmentedImage.getName().equals("matrix")) {
      if(augmentedImage.getTrackingState() == TrackingState.TRACKING &&
         augmentedImage.getTrackingMethod() == AugmentedImage.TrackingMethod.FULL_TRACKING) {
         
         matrixDetected = true;
         Toast.makeText(this, "Matrix tag detected", Toast.LENGTH_LONG).show();

         // AnchorNode placed to the detected tag and set it to the real size of the tag
         // This will cause deformation if your AR tag has different aspect ratio than your video
         anchorNode.setWorldScale(new Vector3(augmentedImage.getExtentX(), 1f, augmentedImage.getExtentZ()));
         arFragment.getArSceneView().getScene().addChild(anchorNode);

         viewRenderableFuture
            .thenAccept(viewRenderable -> {
               viewRenderable.setShadowCaster(true);
               viewRenderable.setShadowReceiver(true);
               viewRenderable.setVerticalAlignment(ViewRenderable.VerticalAlignment.CENTER);
               viewRenderable.setHorizontalAlignment(ViewRenderable.HorizontalAlignment.CENTER);
               TransformableNode modelNode = new TransformableNode(arFragment.getTransformationSystem());
               modelNode.setRenderable(viewRenderable);
               anchorNode.addChild(modelNode);
               modelNode.setWorldRotation(Quaternion.axisAngle(new Vector3(0f, 1f, 0), -180f));

               if (drawable instanceof AnimatedImageDrawable) {
                  ((AnimatedImageDrawable) drawable).start();
               }
            });
         }
   }
}

For WEBP the min API has to be 28, otherwise you have to use GIF.

**Comment by baonq-2356** [comment]
@RGregat thank you so much for your help, but i don't need using .webp file
now my assignment simple is add a RelativeLayout on the matrix image when it detected
![image](https://user-images.githubusercontent.com/73639657/148918008-2bbce696-00dc-40c6-8d82-75808de07948.png)
i refer your code and writting my code is below, but no view added on matrix image, can you let me know what wrong?
my code:
``if (augmentedImage?.trackingState == TrackingState.TRACKING
            && augmentedImage.trackingMethod == AugmentedImage.TrackingMethod.FULL_TRACKING) {
                val anchorNode = AnchorNode(augmentedImage.createAnchor(augmentedImage.centerPose))

                if (!matrixDetected && augmentedImage.name.equals("matrix")) {
                    matrixDetected = true
                    Toast.makeText(this, "Matrix tag detected", Toast.LENGTH_SHORT).show()

                    // AnchorNode placed to the detected tag and set it to the real size of the tag
                    // This will cause deformation if your AR tag has different aspect ratio than your video
                    anchorNode.worldScale = Vector3(augmentedImage.extentX, 1f, augmentedImage.extentZ)
                    arFragment?.arSceneView?.scene?.addChild(anchorNode)

                    val myView = RelativeLayout(this).apply {
                        layoutParams = RelativeLayout.LayoutParams(
                            RelativeLayout.LayoutParams.MATCH_PARENT,
                            RelativeLayout.LayoutParams.MATCH_PARENT
                        )
                    }
                    myView.setBackgroundColor(Color.RED)
                    viewRenderableFuture = ViewRenderable.builder()
                        .setView(this, myView)
                        .build()
                    viewRenderableFuture?.thenAccept { viewRenderable ->
                                Toast.makeText(this, "Successfully to create ViewRenderable", Toast.LENGTH_SHORT).show()
                                viewRenderable.isShadowCaster = true
                                viewRenderable.isShadowReceiver = true
                                viewRenderable.verticalAlignment = ViewRenderable.VerticalAlignment.CENTER
                                viewRenderable.horizontalAlignment = ViewRenderable.HorizontalAlignment.CENTER
                                val modelNode = TransformableNode(arFragment?.transformationSystem)
                                modelNode.renderable = viewRenderable
                                anchorNode.addChild(modelNode)
                                modelNode.worldRotation =
                                    Quaternion.axisAngle(Vector3(0f, 1f, 0f), -180f)
                            }
                            ?.exceptionally {
                                Toast.makeText(this, "Failure to create ViewRenderable", Toast.LENGTH_SHORT).show()
                                null
                            }

                }
        }``

**Comment by RGregat** [comment]
Did you already tried to use a layout file instead of creating the view programmatically?

**Comment by baonq-2356** [comment]
@RGregat 

> Did you already tried to use a layout file instead of creating the view programmatically?

yes, i tried use a layout file as code below, but nothing show when matrix image detected
`val myView = (this.getSystemService(Service.LAYOUT_INFLATER_SERVICE) as LayoutInflater).inflate(R.layout.view_test, null)
                    viewRenderableFuture = ViewRenderable.builder()
                        .setView(this, myView)
                        .build()`
 
 view_test.xml
  `<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="500dp"
    android:layout_height="500dp"
    android:background="@color/red">

</RelativeLayout>`

**Comment by baonq-2356** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="500dp"
    android:layout_height="500dp"
    android:background="@color/red">
    
</RelativeLayout>

**Comment by RGregat** [comment]
I'm just curious, if you add to your layout file a TextView is then something showing up?

**Comment by baonq-2356** [comment]
@RGregat oh wow :D when i add a children view for my layout, it is showed on matrix image, but.. the layout's size did not fit into the matrix image size :( can you help me?

**Comment by RGregat** [comment]
`augmentedImage.getExtentX()` and `augmentedImage.getExtentZ()` should give you the correct size. But the values are in metres. So I guess you have to convert it to pixels or dp somehow, but I have no concrete at the moment without testing a fes things out by myself.

**Comment by baonq-2356** [comment]
@RGregat Excuse me, bro! When matrix image detected, my view is rendered on matrix image, but they look like is not same a plane, my view is not symetry and skewed to the left of matrix image. So, what should i do? 
![image](https://user-images.githubusercontent.com/73639657/149066609-7fbfe9d3-a46f-419e-8c01-8a40eab22cd2.png)

**Comment by baonq-2356** [comment]
@RGregat i think when the matrix image detected then a plane perpendicular to the camera's field of view is created, and my view is rendered onto this plane, because my view always tends to display skewed towards the camera's view angle at the moment matrix image detected
as the image example above

**Comment by RGregat** [comment]
`wrap_content` is the key!

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="#CC1212">

    <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="TextView"
        android:textSize="60sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by baonq-2356** [comment]
@RGregat sorry but it didn't work
```kotlin
.thenAccept { viewRenderable ->
    viewRenderable.isShadowCaster = true
    viewRenderable.isShadowReceiver = true
    viewRenderable.verticalAlignment = ViewRenderable.VerticalAlignment.CENTER
    viewRenderable.horizontalAlignment = ViewRenderable.HorizontalAlignment.CENTER
    viewRenderable.sizer = FixedWidthViewSizer(augmentedImage.extentX)
    val modelNode = TransformableNode(arFragment?.transformationSystem)
    anchorNode.addChild(modelNode)
    modelNode.renderable = viewRenderable
    // For some reason it is shown upside down so this will rotate it correctly
    modelNode.worldRotation = Quaternion.axisAngle(Vector3(0f, 1f, 0f), -180f)
}
```
and my_view.xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="#CC1212">

    <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="TextView"
        android:textSize="60sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by ThomasGorisse** [comment]
Your `TextView` width and height must be `0dp` if you want it to fit the parent.
Not `wrap_content`

**Comment by baonq-2356** [comment]
@ThomasGorisse yeah i agree that set `TextView` width and height is `0dp` because i use `ConstraintLayout`. But it doesn't the key yet. I changed my layout to `FrameLayout` but it didn't work correct, if i still use `ConstraintLayout' then i get same wrong result :(
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="#CC1212">

    <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="TextView"
        android:textSize="60sp" />
</FrameLayout>
```
You can join to discussions: https://discord.com/channels/893787194295222292/895209031700979752/931104008716820491
