### ISSUE TITLE
How to control the initial size of the model?

### ISSUE THREAD

**Issue by Yeafun** [SceneView/sceneform-android#283]
Thank you very much for the open source, I tried all the samples with great results and even put a 4 meters tall tyrannosaurus rex in our school, but I didn't want it to be that big initially because it was too close causing me to have to retreat a long way to see it

**Comment by grassydragon** [comment]
Hi!
You can use the Filament bounding for scaling the model: https://github.com/SceneView/sceneform-android/discussions/243#discussioncomment-1832858
