### ISSUE TITLE
Is session resumed and paused automatically?

### ISSUE THREAD

**Issue by sarimmehdi** [SceneView/sceneform-android#297]
I was looking at this [sample](https://github.com/SceneView/sceneform-android/blob/master/samples/ar-model-viewer-java/src/main/java/com/google/ar/sceneform/samples/gltf/MainActivity.java) and I noticed that there is no onPause, onResume, or onDestroy method being overridden. In the original Sceneform, if I recall correctly, we would have to resume and pause the session automatically.

**Comment by grassydragon** [comment]
Yes, it is paused and resumed automatically in the `BaseArFragment`: https://github.com/SceneView/sceneform-android/blob/master/ux/src/main/java/com/google/ar/sceneform/ux/BaseArFragment.java#L245

**Comment by ThomasGorisse** [comment]
@sarimmehdi Please use discussion

**Comment by sarimmehdi** [comment]
@ThomasGorisse apologies, I forgot to use the discussion tab for this. I will close this now as it is not an issue and just a simple question
