### ISSUE TITLE
Update Filament to version 1.17.0 (or higher)

### ISSUE THREAD

**Issue by jakub-cosmose** [SceneView/sceneform-android#301]
The currently used version of the Google Filament library contains a serious bug, that always eventually leads a to native crash (global reference table overflow). Sometimes it's after 40 minutes, sometimes after 2 (it highly depends on the model), but it's unavoidable. You can read more about the symptoms here: https://github.com/google-ar/arcore-android-sdk/issues/1315
The fix has been released in version 1.17.0 (see https://github.com/google/filament/issues/4957).
The update requires both bumping the version in gradle files and re-generating filament assets.

**Comment by RGregat** [comment]
Thx for the information, we will update Filament ASAP

**Comment by RGregat** [comment]
@jakub-cosmose the master branch has now up to date dependencies. See also https://github.com/SceneView/sceneform-android/pull/303

**Comment by jakub-cosmose** [comment]
Thanks a lot. I can't wait to see the next release :)

**Comment by ThomasGorisse** [comment]
@jakub-cosmose Are you sure that your bug comes from Filament since the one reported in the ARCore repo happens with a non Filament (ARCore sample) usage?

**Comment by jakub-cosmose** [comment]
That's a good question :) What I know is that there was a confirmed problem in Filament that I experienced myself in my app. I also know that after upgrading Filament I wasn't able to reproduce it anymore. Is the problem described in the ArCore repo exactly the same one? This is hard to tell. The issue there has been marked as "fixed in upcoming release" and that happened before the latest release, so maybe there was a different problem that has been already solved?
