### ISSUE TITLE
The GLB file postion is not set on face its show on top 

### ISSUE THREAD

**Issue by Amitdygon** [SceneView/sceneform-android#302]
.glb file postion is not write its always show on the top how can i set the 3D model into center 
setRecenterMode(RenderableSource.RecenterMode.CENTER)

Here i attach my glb file https://drive.google.com/file/d/1M2OwRKvtu-vfDtLOAbI3wqZb73XxU779/view?usp=sharing

**Comment by grassydragon** [comment]
Hi!
You need to change your model to use our template here: https://github.com/SceneView/sceneform-android/blob/master/samples/augmented-faces/assets-sources/models/fox.blend
The `README.md` file has been updated recently to include more information on how to use the template.
