### ISSUE TITLE
How to report progress when downloading a model?

### ISSUE THREAD

**Issue by jakub-cosmose** [SceneView/sceneform-android#312]
I want to display a GLB file which is downloaded from the Internet. The download takes some time, so I'd like to inform the user about the progress. How to do that? I see that the `Renderable.Builder` has the field `private LoadGltfListener loadGltfListener`, but there's no method to set its value and I think that this listener is never notified. Apart from that it can't be used to report progress. It has a method like `void reportBytesDownloaded(long bytes)`, but there's no information about the file total size.

**Comment by grassydragon** [comment]
Hi!
Yes, as you've mentioned reporting the download progress isn't currently supported. However, we may consider this as an improvement for the new [SceneView](https://github.com/SceneView/sceneview-android) library. We are using [Fuel](https://github.com/kittinunf/fuel) as an HTTP client there and it can report progress: https://github.com/kittinunf/fuel/blob/master/fuel/README.md#adding-progress-callbacks

**Comment by ThomasGorisse** [comment]
```kotlin
ResourceLoader.fuelManager.addRequestInterceptor { { request: Request ->
    request.requestProgress { readBytes, totalBytes ->  }
}}
```
BUT on Sceneform (not on SceneView), models are still loaded with the old CompletableFuture way.
You can use the ResourceLoader and create your model from the byte result our use your own download way.
