### ISSUE TITLE
phone surface turns out to be black

### ISSUE THREAD

**Issue by chenleicrm** [SceneView/sceneform-android#315]
![Screenshot_20220218-104636_SceneFormDemo](https://user-images.githubusercontent.com/10569293/154608495-84d4a252-1b54-4594-8b90-ada50ffdcd11.jpg)
As you can see. Phone modal surface is black when I use REALISTIC or SPECTACULAR config
![Screenshot_20220218-105430_SceneFormDemo](https://user-images.githubusercontent.com/10569293/154608838-496d71e4-0077-467f-a0bd-120b9a254785.jpg)
And phone modal surface turns out to be oranged when I use DISABLED mode

**Comment by chenleicrm** [comment]
I wonna to know why the phone is oranged and how to disable

**Comment by chenleicrm** [comment]
[maldives_blue.zip](https://github.com/SceneView/sceneform-android/files/8093819/maldives_blue.zip)
the glb file is in the zip above

**Comment by ThomasGorisse** [comment]
Hi,
Can you confirm that you also don't see the screen with AMBIENT_INTENSITY?
Can you send a screenshot of your model screen material within Blender?

**Comment by ThomasGorisse** [comment]
If well defined, the phone screen should be emissive to work in real (AR) usage.

**Comment by chenleicrm** [comment]
> Hi, Can you confirm that you also don't see the screen with AMBIENT_INTENSITY? Can you send a screenshot of your model screen material within Blender?
<img width="523" alt="WX20220219-172313@2x" src="https://user-images.githubusercontent.com/10569293/154794999-6f52e65c-47f2-4fba-b315-a76a83d22d57.png">
here is the screenshot of the model screen and you can also see the glb file in maldives_blue.zip above

**Comment by chenleicrm** [comment]
I  can see the model screen but need to rotate the modal or put it on the desk not on the floor when i open the light estimate

**Comment by chenleicrm** [comment]
> If well defined, the phone screen should be emissive to work in real (AR) usage.

I just use the model view demo code and replace the model file

**Comment by ThomasGorisse** [comment]
> > If well defined, the phone screen should be emissive to work in real (AR) usage.
> 
> I just use the model view demo code and replace the model file 

I meant change the emissive from Blender.
As we can see in your Blender screenshot, the phone screen doesn't seems to emit lights. So just like in real world, if your phone screen is "turned off" nothing will be "visible"

**Comment by chenleicrm** [comment]
Is this screenshot also doesn't emit light ?
<img width="429" alt="WX20220219-174924@2x" src="https://user-images.githubusercontent.com/10569293/154795908-fabcf70a-8033-4d44-a23a-9ad0b0dc6c3b.png">

**Comment by chenleicrm** [comment]
> > > If well defined, the phone screen should be emissive to work in real (AR) usage.
> > 
> > 
> > I just use the model view demo code and replace the model file
> 
> I meant change the emissive from Blender. As we can see in your Blender screenshot, the phone screen doesn't seems to emit lights. So just like in real world, if your phone screen is "turned off" nothing will be "visible"

but when i rotate the modal to the direction of light , i can see the phone screen...

**Comment by chenleicrm** [comment]
Do you mean the phone screen is not emit light , so the screen is "turn off",  when i rotate the model  screen to the light . it can "turn on" ?

**Comment by ThomasGorisse** [comment]
> Is this model emiting light ?

Your model material is made of a single linear image texture so you have to modify it properties inside Blender if you want your screen to be lighter and emissive and keep the rest as a standard phone material.

**Comment by ThomasGorisse** [comment]
This is your texture
![image](https://user-images.githubusercontent.com/6597529/154796775-34e85068-1386-49e1-b9a0-70a7bbfbff4e.png)
To explain you shortly what is happening, just imagine what would happen in real life if you printed the bellow image on a paper and paste it on something having the same shape as a phone. If your room is a even a little dark, you won't see it well because it won't have any reflections or the fake screen won't emit any light.

**Comment by chenleicrm** [comment]
OK I will try this next week ,and I also want to know why the model is oranged when i disable the light estimate

**Comment by ThomasGorisse** [comment]
Your model has a well define material for the phone structure (metal) but not for the screen part:
![image](https://user-images.githubusercontent.com/6597529/154797032-ceb8af4c-1fa0-410f-96f4-d6cad50e8f4d.png)

**Comment by ThomasGorisse** [comment]
Here you can see that you only have black `Emission`
![image](https://user-images.githubusercontent.com/6597529/154797082-34049d85-e964-4ff8-92e2-a9443bace913.png)

**Comment by chenleicrm** [comment]
> Here you can see that you only have black `Emission` ![image](https://user-images.githubusercontent.com/6597529/154797082-34049d85-e964-4ff8-92e2-a9443bace913.png)

thanks for your patience

**Comment by chenleicrm** [comment]
> ![Screenshot_20220218-104636_SceneFormDemo](https://user-images.githubusercontent.com/10569293/154608495-84d4a252-1b54-4594-8b90-ada50ffdcd11.jpg) As you can see. Phone modal surface is black when I use REALISTIC or SPECTACULAR config ![Screenshot_20220218-105430_SceneFormDemo](https://user-images.githubusercontent.com/10569293/154608838-496d71e4-0077-467f-a0bd-120b9a254785.jpg) And phone modal surface turns out to be oranged when I use DISABLED mode

Can you help to check the second picture. When i disable the light estimate. the phone model is oranged

**Comment by ThomasGorisse** [comment]
This might be a FILMIC issue we solved on the today release 1.20.5.
Please update your depency version, and post the same screenshot.

**Comment by chenleicrm** [comment]
> This might be a FILMIC issue we solved on the today release 1.20.5. Please update your depency version, and post the same screenshot.
![Screenshot_20220220-154541](https://user-images.githubusercontent.com/10569293/154826409-4948a002-a24e-49c2-b30c-7d4a8647fbdc.png)

here is the picture I update depency version to 1.20.5

**Comment by chenleicrm** [comment]
https://user-images.githubusercontent.com/10569293/154829616-e4a3afa6-96c9-41a9-9385-2ceb54888f88.mp4

As you can see, in this video, phone surface turns to be black gradually. Is this also the problem of model image texture ?

**Comment by chenleicrm** [comment]
I try many times, phone model surface is always show black only in the direction where i just place it on the plane. and show normal when i rotate the model to other direction

**Comment by chenleicrm** [comment]
> AMBIENT_INTENSITY

I can see the screen in AMBIENT_INTENSITY 

> AMBIENT_INTENSITY

I can see the screen with AMBIENT_INTENSITY

**Comment by ThomasGorisse** [comment]
You have to modify a little bit your model.
Some properties in it may come from an `.obj` or `.fbx` import and has to be changed a little bit to make it completely glTF PBR 3D engine ready.
For exemple, here is how the `metallic` and `roughness` factors are made of inside your material:

| ![image](https://user-images.githubusercontent.com/6597529/154925382-100b5f73-8609-48b6-af81-2a1e0303a330.png) | ![image](https://user-images.githubusercontent.com/6597529/154926133-9a476a2e-d786-4e59-ba01-0f9c1116dfc5.png) |
| - | - |

Meaning roughness is extracted from the Green channel and Metalic from the Blue of the right image

You have 3 choices: 
1. Modify the `Image_1` image
2. Separate parts of your phone inside Blender and apply metallic for phone structure and emission for the phone screen
3. Completely disable environment lighting influence within Sceneform

@grassydragon Do you remember how to disable lighting influence on an object?

**Comment by grassydragon** [comment]
> Do you remember how to disable lighting influence on an object?

It can be done like that or using an RGB node as an input to Surface: https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html?#exporting-a-shadeless-unlit-material

**Comment by ThomasGorisse** [comment]
I was more thinking of a Filament way to do it.

**Comment by chenleicrm** [comment]
yes I want to disable the lighting influence on model in code when I set light estimate DISABLED @ThomasGorisse @grassydragon

**Comment by chenleicrm** [comment]
I change build dependencies to 1.18.10 , the model surface is show OK

**Comment by chenleicrm** [comment]
any update now. cause our program is on emergency about the model effect @ThomasGorisse @grassydragon

**Comment by ThomasGorisse** [comment]
Please consider sponsoring us if you need any urgent help.
Because we already bring you precise answers and we also got our own "emergency" private remunerating things to do.

**Comment by chenleicrm** [comment]
I agree with it . I have no right to make sponsoring in our team cause i am just an engineer ...

**Comment by chenleicrm** [comment]
I just think we can make this repo more complete and easy to use or it can be called open source spirit

**Comment by chenleicrm** [comment]
Hi I have become a sponsor and now I wanna to know how to disable the lighting influence on model in code when I set light estimate DISABLED

**Comment by grassydragon** [comment]
Thank you! We will devote some time to see how this can be done.

**Comment by grassydragon** [comment]
The yellow color comes from the default HDR environment as it is described in this issue: https://github.com/SceneView/sceneform-android/issues/322#issuecomment-1049192113
The solution is to find a more suitable environment or generate a pure white environment at runtime: https://github.com/google/filament/discussions/3483#discussion-2561539
Using an `InderectLight` is the only way to set the ambient lighting in Filament.

@ThomasGorisse what is the best way to generate a pure white environment in your opinion?

**Comment by ThomasGorisse** [comment]
Setting the environment indirect light to null and increasing the main light should do the job but you won't have any reflection on the model:
```kotlin
sceneView.environment = sceneView.environement.apply {
    indirectLight = null
    skybox = null
} 
```
Another solution would be to use a white standard studio HDR like this one:
https://github.com/SceneView/sceneview-android/tree/main/samples/model-viewer/src/main/assets/environments

```kotlin
sceneView.environment.indirectLight = HDRLoader.loadEnvironment( context = requireContext(), hdrFileLocation = "environments/studio_small_09_2k.hdr", specularFilter = false ).indirectLight
```

**Comment by ThomasGorisse** [comment]
Even if it should be possible to use the `IndirectLight.Builder` to create a white environment with maybe some white texture reflection and irradiance, you could also simply open the previous .hdr with Gimp. Clear all to white and use it like mentioned before.
Once it looks ok for you, just generate the ktx and use the `KTXLoader` instead of `HDRLoader` and the final consumption result should not be so far.

**Comment by ThomasGorisse** [comment]
But one more time, this is not an environment issue but a wrong model material issue.
A black phone metal material should not reflect its environment like this.
It usually happens when trying to convert an fbx to Gltf without manually modifying the material nodes.
A really better choice would be to use a Principled BSDF standard material model.

**Comment by chenleicrm** [comment]
Thanks for your professional answer, Is there a java way to change the environment.indirectLight of the sceneView ?

**Comment by grassydragon** [comment]
> Setting the environment indirect light to null and increasing the main light should do the job but you won't have any reflection and everything on the model should look a little flat

I've tried that and since the main light is a directional light the model is lit only from this direction and is black from the opposite direction since there is no ambient light.

**Comment by grassydragon** [comment]
> Is there a java way to change the environment.indirectLight of the sceneView

Yes, the extension methods can be accessed from the `[FileName]Kt` class and take the extended class instance as the first parameter.

**Comment by chenleicrm** [comment]
Is there any demo code in java  since I am new here @grassydragon @ThomasGorisse

**Comment by grassydragon** [comment]
Here are the required changes for the Java sample application to disable the light estimation and load the alternative environment. However, the model doesn't look good in this case, particularly, the reflections: 
https://photos.app.goo.gl/BckDnWogzjKwjmDz7

I'm not sure what is the problem because it neither appears with the default environment nor when I open the model and new environment in the [glTF Sample Viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/):

![image](https://user-images.githubusercontent.com/35110066/157827229-8cd103b1-644d-40fd-a7f6-3ea2fcae04df.png)

[sample-ar-model-viewer-java.txt](https://github.com/SceneView/sceneform-android/files/8230053/sample-ar-model-viewer-java.txt)

@chenleicrm Can you try opening the model in [the Filament glTF sample viewer](https://github.com/google/filament/tree/main/android/samples/sample-gltf-viewer) to see if the problem is related to the combination of Filament and your model?

**Comment by chenleicrm** [comment]
I have try your demo code and phone surface shows OK in light estimate disable mode. genius work~ I will keep learning about this

**Comment by chenleicrm** [comment]
I think its time to close this issue and thanks to your patience and professional explain @ThomasGorisse

**Comment by ThomasGorisse** [comment]
Thanks for your financial contribution and the detailed issue report.
Hope to see the SceneView logo inside your phone 3d model next time instead of "Spark" which may suggest that your app is using Spark AR 😄

**Comment by chenleicrm** [comment]
I think SceneView logo will appear on our product surface if it pass our test in next one or two weeks  😄
