### ISSUE TITLE
Disappearing model textures (only) on camera move 

### ISSUE THREAD

**Issue by kustraslawomir** [SceneView/sceneform-android#321]
Hello, how to prevent disappearing model from the scene on camera movement? https://youtu.be/MsX_vSy7YoM

**Comment by kustraslawomir** [comment]
@ThomasGorisse I didn't find any issues like this in your samples. But it exists with my models, maybe You know what to do? Thank you mate

**Comment by kustraslawomir** [comment]
Only textures are missing, the shadow is still visible, viewRenderables are still visible...

**Comment by kustraslawomir** [comment]
Hmm, I have used my own model in Your samples and the behavior is the same, textures are not visible when moving the camera a little bit off the model. 
Glb: https://we.tl/t-qL66DAptRL
I could provide you .blend project if You wish. If you don't have time for this - that is ok, I understood. Thank you <3

**Comment by kustraslawomir** [comment]
https://youtube.com/shorts/inbFl2F_7Co?feature=share

**Comment by kustraslawomir** [comment]
sample-ar-model-viewer-java

**Comment by kustraslawomir** [comment]
` ModelRenderable.builder()
                .setSource(this, Uri.parse("models/VAMPIR3_optymized.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    MainActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model = model;
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });`

**Comment by kustraslawomir** [comment]
Also I have used fox.blend and pasted the .fbx from https://www.mixamo.com/, same results. :(

**Comment by ThomasGorisse** [comment]
Your issue comes from the view culling which doesn't render models when any part of its bounding box is within the camera view.
There is actually a wrong bounding box calculation within Filament when the model is animated so the culling system thinks that parts of your models are not visible within the rendered view even if they currently are.

We had a culling setter at the `RenderableInstance` level (commit: bdc7ea9c0403e689ad5e915895c0ae6391f7303a)

For now, you have to call
```java
renderableInstance.setCulling(false)
```

**Comment by kustraslawomir** [comment]
@ThomasGorisse It worked! Thank you very very much <3

**Comment by ThomasGorisse** [comment]
You're welcome.
You can think about sponsoring us if you appreciate our work.
