### ISSUE TITLE
Support FilamentAsset child entities

### ISSUE THREAD

**Issue by MarcoGoe** [SceneView/sceneform-android#325]
Hello,

we have created a model with multiple child nodes and would like to receive the clicked child node. 

So for example we have a model containing two cubes. When the user presses cube_1 we would like to start the animation of cube_1 and same for cube_2.
![grafik](https://user-images.githubusercontent.com/74299420/156136465-fe8b8772-e03d-4ea2-9417-5c6525cc5f7f.png)

In Scenekit for iOS this seems to be really easy. You can access a list of the child nodes and with a hit test you also get the clicked child node.

With Sceneform for Android and the glb model I was not able to get this working. You can access the different animations and the different materials. But not the child nodes and which one the user clicked. I found those old issues in the archived sceneform sdk:
https://github.com/google-ar/sceneform-android-sdk/issues/63
https://github.com/google-ar/sceneform-android-sdk/issues/206

Is there any progress on that? And is there a better way to achive that than just adding two models to seperate nodes?

Thanks!

**Comment by ThomasGorisse** [comment]
Hi,

Unfortunately there won't be any progress on this part inside [sceneform-android](https://github.com/SceneView/sceneform-android)

You will have to move to [sceneview-android](https://github.com/SceneView/sceneview-android) and wait a little for us to add the Filament Pick API which will enable the feature you describe for any child entity inside your model.

Maybe, you could think of sponsoring or contributing in order to speed it up since we hardly find time to spend on specific features those days.
We have to work on remunerative apps instead of here because of missing sponsors.
[Sponsor SceneView](https://opencollective.com/sceneview/contribute/bronze-sponsor-34718/checkout)

Thanks

**Comment by grassydragon** [comment]
Hi @MarcoGoe!
This was supported in SceneView in this pull request: https://github.com/SceneView/sceneview-android/pull/96

**Comment by weijiaqi** [comment]
> 你好，
> 
> 我们创建了一个具有多个子节点的模型，并希望接收单击的子节点。
> 
> 例如，我们有一个包含两个立方体的模型。当用户按下 cube_1 时，我们希望启动 cube_1 的动画，对于 cube_2 也是如此。 ![涂鸦](https://user-images.githubusercontent.com/74299420/156136465-fe8b8772-e03d-4ea2-9417-5c6525cc5f7f.png)
> 
> 在适用于 iOS 的 Scenekit 中，这似乎非常简单。您可以访问子节点的列表，并且通过命中测试，您还可以获得单击的子节点。
> 
> 使用适用于 Android 的 Sceneform 和 glb 模型，我无法使其正常工作。您可以访问不同的动画和不同的材料。但不是子节点以及用户单击的哪个节点。我在归档的sceneform sdk 中发现了那些旧问题： [google-ar/sceneform-android-sdk#63 ](https://github.com/google-ar/sceneform-android-sdk/issues/63) [google-ar/sceneform-android-sdk#206](https://github.com/google-ar/sceneform-android-sdk/issues/206)
> 
> 这方面有什么进展吗？除了将两个模型添加到单独的节点之外，还有更好的方法来实现这一点吗？
> 
> 谢谢！



> 你好，
> 
> 我们创建了一个具有多个子节点的模型，并希望接收单击的子节点。
> 
> 例如，我们有一个包含两个立方体的模型。当用户按下 cube_1 时，我们希望启动 cube_1 的动画，对于 cube_2 也是如此。 ![涂鸦](https://user-images.githubusercontent.com/74299420/156136465-fe8b8772-e03d-4ea2-9417-5c6525cc5f7f.png)
> 
> 在适用于 iOS 的 Scenekit 中，这似乎非常简单。您可以访问子节点的列表，并且通过命中测试，您还可以获得单击的子节点。
> 
> 使用适用于 Android 的 Sceneform 和 glb 模型，我无法使其正常工作。您可以访问不同的动画和不同的材料。但不是子节点以及用户单击的哪个节点。我在归档的sceneform sdk 中发现了那些旧问题： [google-ar/sceneform-android-sdk#63 ](https://github.com/google-ar/sceneform-android-sdk/issues/63) [google-ar/sceneform-android-sdk#206](https://github.com/google-ar/sceneform-android-sdk/issues/206)
> 
> 这方面有什么进展吗？除了将两个模型添加到单独的节点之外，还有更好的方法来实现这一点吗？
> 
> 谢谢！



> 

we have created a model with multiple child nodes and would like to receive the clicked child node.How did you finally implement it in java?
