### ISSUE TITLE
graphics memory can not be released ...

### ISSUE THREAD

**Issue by chenleicrm** [SceneView/sceneform-android#326]
Graphics memory can not be released after the activity finished in latest version 1.20.5.  Is there any to release the graphics memory totally

![memory_leak](https://user-images.githubusercontent.com/10569293/156289348-d8edfa6b-83da-4e81-b2e0-9b1dfbd9043f.png)

**Comment by ThomasGorisse** [comment]
There are a lot of discussion around this subject in here. Please make a quick search on the issues and discussions section.

If you really want a complete cleaning on destroy usage, you will have to move to [sceneview-android](https://github.com/SceneView/sceneview-android) which has a greater memory management thanks to lifecycle aware components.
