### ISSUE TITLE
Out of Memory exception when switching multiple 3D Models in Non AR Sceneform usage case

### ISSUE THREAD

**Issue by monsterbrain** [SceneView/sceneform-android#333]
We are using sceneform for showing several animated 3d Models (glb files) in a non AR activity.

We have option for selecting different type of models via menu.

Models are around 7MB to 10MB in range w.r.t size, and contains animations.

On Selecting each model, previously loaded model node will be removed from the arSceneView and new model is loaded and added to scene. After selecting few models app will Crash due to memory exception.

Checking the Profiler, we found that on each model selection, memory keeps on increasing, until it crashes. We tried clearing using the Renderable static function, but keeps crashing. It seems like removing the node doesn't clear the memory allocated for loaded 3d Model. Is there any way to clean up the memory used by the memory model using filament or ar core ?

**Comment by chenleicrm** [comment]
I also meet this problem cause graphics memory can not be released and keep grow which may cause the out of memory crash

**Comment by ThomasGorisse** [comment]
If you need a more memory friendly usage, you will have to move to [SceneView](https://github.com/SceneView/sceneview-android) which rely on Lifecycle aware components and on `destroy()` functions declared on every consuming components.
Sceneform memory releasing was originally based on variables references released so you can't really rely on it.
