### ISSUE TITLE
when will Filament version upgrade to 1.20.3 

### ISSUE THREAD

**Issue by chenleicrm** [SceneView/sceneform-android#343]
cause filament has some bug fix in latest version

**Comment by ThomasGorisse** [comment]
You can make a PR to move to the latest Filament version but take care of recompiling the materials

**Comment by MrCsabaToth** [comment]
dup of #368?

**Comment by ThomasGorisse** [comment]
Fixed: Release 1.21.0 : [Controlling Renderable culling + Fixed destroying skybox + ARCore 1.31.0 + Filament 1.21.1](https://github.com/SceneView/sceneform-android/releases/tag/v1.21.0)
