### ISSUE TITLE
Vertical Detections and Placement 

### ISSUE THREAD

**Issue by CapelaA10** [SceneView/sceneform-android#349]
Hey. 

Doing the implementation we found out that ARCore whitout sceneview is able to detect vertical walls with just one color.
Like in the example by google hello_ar_java, that is working.

But with sceneview that was not the case. Changing the config from HORIZONTAL_VERTICAL or just VERTICAL in the plane finding mode, doesn't make a difference.

We know that it's possible and we see a lot of "default" implementations of ArCore doing this.
This is an issue? This will be fixed? What can we expect SceneView to do about this?

**Comment by CapelaA10** [comment]
Hey @grassydragon, we created this zip with the 2 examples one from sceneview and the other one from the hello_ar_java

As we can see in the sceneview when trying to push the object to the upper side of the wall, the object doesn't go up, we only can place the object in objects in front of the wall, if the wall is just one color he doesn't let us put the object.

But on the hello_ar_java we can see that the example lets us put the object on the vertical wall direct, we know we are using a transformable node in the sceneview but this is just us trying to move the object and placing it.

Link to download the videos in .zip: https://mega.nz/file/b0kwWDqI#U_SzndSxVGf2REfGKD2OypdIYcrREXDesCcL7wJAWn4

Thanks for your time.

**Comment by grassydragon** [comment]
Hi!
The hello_ar_java sample also uses the `Point`, `InstantPlacementPoint` and `DepthPoint` trackables to place the object: https://github.com/google-ar/arcore-android-sdk/blob/e271aa3304afae21a1f64a1e2e5bd82ee44d49e3/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/HelloArActivity.java#L633

The depth placement is helpful for plain walls but it is only supported in SceneView and not in Sceneform (we are adding new features only to SceneView). However, you can implement it yourself if needed.

**Comment by CapelaA10** [comment]
Hey @grassydragon, thanks a lot for the info, this will help a lot.
I will close on this comment.

Have a great week of work, wish all the best to all the community.
One more time, thanks for your time :D
