### ISSUE TITLE
I set the glb model I made by myself and can't load it ,help me

### ISSUE THREAD

**Issue by LotusWallet** [SceneView/sceneform-android#350]
ModelRenderable.builder()
                    .setSource(context, Uri.parse("https://download.redph.cn/meta/ar/shuixing.glb"))
                    .setIsFilamentGltf(true)
                    .setAsyncLoadEnabled(true)
                    .build()

**Comment by LotusWallet** [comment]
I am a static image, I can use it normally in sceneform1.17.1

**Comment by LotusWallet** [comment]
I am a static 3d model, I can use it normally in sceneform1.17.1

**Comment by grassydragon** [comment]
Hi!
You need to center your model at the origin in Blender. Also there is no need to export the cameras.
[shuixing-adjusted.zip](https://github.com/SceneView/sceneform-android/files/8383328/shuixing-adjusted.zip)
