### ISSUE TITLE
Renderable.getSubmeshCount() always return 0

### ISSUE THREAD

**Issue by Schlewinow** [SceneView/sceneform-android#354]
Currently migrating an app from sceneform 1.15.0 (old Google version) to 1.20.5 of this new version.
Debugging an issue with materials not being applied anymore (after recompiling the materials with the proper version of filament matc) I stumbled upon the issue that for our ModelRenderables the method getSubmeshCount() always returns 0 for every model. The models are GLB-files and rendered properly in an AR scene, but iterating over the submeshes to apply materials is not possible because the submesh count is always 0. The expected value for a rendered mesh should always be at least 1 though.
This seems to be an issue since 1.16.0 and was probably never fixed (https://github.com/google-ar/sceneform-android-sdk/issues/1049).

Is there any way of getting the submesh count for renderables (from GLBs) in the current sceneform version?
And how would a material be applied to a submesh of a RenderableInstance?

**Comment by tapmyads-dev1** [comment]
We are also having same issue. Can anyone please provide input on this?

**Comment by WangChangQin** [comment]
same issue + 1
