### ISSUE TITLE
Pale 3D model

### ISSUE THREAD

**Issue by kelvinwatson** [SceneView/sceneform-android#357]
I'm noticing sometimes my 3D model (glb) loads and appears pale/lighter (right screenshot), like there's a layer over top of it. Any idea why this could be? 

Note this is happening only occasionally (approximately 1 in 35 loads). Most of the time, it loads properly (left screenshot).

<img src="https://user-images.githubusercontent.com/11381360/163597538-eb552395-670b-4b3e-ad9a-7d736b1cc3c2.png" width="300"> <img src="https://user-images.githubusercontent.com/11381360/163597532-ea741860-476e-4644-990d-ceb1399af838.png" width="300"> 
 
```
        ModelRenderable.builder()
            .setSource(context, Uri.parse(uri))
            .setIsFilamentGltf(true)
            .setRegistryId(uri)
            .build()
            .thenAccept { modelRenderable: ModelRenderable ->
```

**Comment by ThomasGorisse** [comment]
Try reducing the `environment.indirectLigth.intensity`

**Comment by kelvinwatson** [comment]
@ThomasGorisse  This bug doesn't happen every time though, so not sure I want to change the intensity across the board.
