### ISSUE TITLE
App crashes while opening ar camera

### ISSUE THREAD

**Issue by udayk07** [SceneView/sceneform-android#358]
While loading a simple AR screen in pixel2/one plus nord devices, facing below crash issue in ar camera. Issue not reproducible few of our test devices ( Samsung galexy s9, s9+, F64 ). Facing issue in pixel and one plus nord devices only. 

`Failed to populate image metadata for CPU image. camera_stream_id={camera_id = "0", stream_index = 0}, status=UNAVAILABLE: 
    ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:896
    IMU-camera offset for camera not initialized. camera_id=0`

We are Using updated are ar-core services only ( 1.30.22). Could anyone help us to solve the issue ? 
Thank you.

Full crash log:
[ar_crash_pixel_test.txt](https://github.com/SceneView/sceneform-android/files/8532000/ar_crash_pixel_test.txt)

**Comment by devbridie** [comment]
This may not be ARCore related; looking at the tombstone--

```
#00 pc 000000000008246c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 5812256023147338b8a9538321d4c456)
#01 pc 000000000016bed0  /data/app/com.test.ar.a-_TbEHP0UHv9fIi-HzDa9oA==/lib/arm64/libfilament-jni.so (utils::TPanic<utils::PreconditionPanic>::panic(char const*, char const*, int, char const*, ...)+192) (BuildId: f970bc55c73f5308754d01f0a832b184139854ea)
```

Could you also include the bits above the tombstone? I would think that the libfilament panic would be accompanied by an error message which was not included in the log; thanks.
