### ISSUE TITLE
My glb format graphics are super large，help

### ISSUE THREAD

**Issue by LotusWallet** [SceneView/sceneform-android#359]

**Comment by LotusWallet** [comment]
https://download.redph.cn/meta/ar/all.glb

**Comment by grassydragon** [comment]
Hi!
@RGregat has shared a video about reducing the model size on our Discord server: https://www.youtube.com/watch?v=VyktzazqNJs

**Comment by LotusWallet** [comment]
> 你好！ @RGregat在我们的 Discord 服务器上分享了一个关于减小模型大小的视频：[https ://www.youtube.com/watch?v=VyktzazqNJs](https://www.youtube.com/watch?v=VyktzazqNJs)

Thanks for your hard work。
