### ISSUE TITLE
Cannot run the sample-ar-model-viewer-java

### ISSUE THREAD

**Issue by CineOP** [SceneView/sceneform-android#361]
I downloaded code from the Github code page, opened the master branch as AndroidStudio project, builded it and tried to run on AndroidStudioEmulator. It throwed the next error:

_`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.ar.sceneform.samples.gltf/com.google.ar.sceneform.samples.gltf.MainActivity}: java.lang.IllegalStateException: Couldn't create Engine`_

- AndroidStudio version:  2021.1.1 Patch 2
- AndroidStudioEmulator version: Android 10.0 API 29 x86
- Graddle: bundled 211.7628.21.2111.8193401
- OS: Windows 10 x64
- RAM: 16Gb
- VM: enabled
- sceneform version: Just downloaded from GitHub
- JDK: 1.8
- Java: 1.8
- ARGooglePlayServices: 1.30.0_x86_for_emulator
- Full log: [log.txt](https://github.com/SceneView/sceneform-android/files/8568041/log.txt)

What can I do?

**Comment by grassydragon** [comment]
Hi!
It looks like OpenGL ES 3 isn't supported by the emulator. Can it be the case on your computer?

**Comment by ThomasGorisse** [comment]
https://sceneview.github.io/sceneform-android/emulator

**Comment by CineOP** [comment]
Thank you very much! Setting the advanced render settings to Desktop native GL/Renderer maximum helped.
