### ISSUE TITLE
Video very bright, not in original colors

### ISSUE THREAD

**Issue by jnocz** [SceneView/sceneform-android#364]
Hi, 
I'm playing with sample-augumented-images sample project and trying to use my own video, the image tracker is recognized, video starts playing, but is very light ( attached a screenshot of original video and sample app). Is there any settings I can change to display video with original colors? Thank you.

<img width="754" src="https://user-images.githubusercontent.com/18227723/165957619-996b1537-1262-478d-a5ea-a42239f3cf33.png">

<img width="754" src="https://user-images.githubusercontent.com/18227723/165958174-3c70e9ff-c235-4872-94ab-17679ebb4aaa.png">

**Comment by grassydragon** [comment]
Hi!
You can try the solution described in this discussion: https://github.com/SceneView/sceneform-android/discussions/348

**Comment by jnocz** [comment]
Hi, it helped, thank you!
