### ISSUE TITLE
Texture issue v1.21.0

### ISSUE THREAD

**Issue by kustraslawomir** [SceneView/sceneform-android#369]
Hello, after the update to [v1.21.0](https://github.com/SceneView/sceneform-android/tree/v1.21.0), my AR characters have texture issues visible on screen. 
**These 2 models are built from the same .glb file.** Maybe you know the issue @ThomasGorisse? Thank you 
![photo_2022-05-18_09-27-11 (2)](https://user-images.githubusercontent.com/16974890/168982427-d9d82acb-335f-4ca9-b399-500d74fac321.jpg)

```
    private fun glbFromInternalStorage(
        context: Context,
        modelPath: String
    ): CompletableFuture<ModelRenderable>? {
        return ModelRenderable.builder()
            .setSource(
                context,
                Uri.parse(modelPath)
            )
            .setIsFilamentGltf(true)
            .setAsyncLoadEnabled(true)
            .build()
    }
```

**Comment by kustraslawomir** [comment]
After changing **setAsyncLoadEnabled to false** there is no issue anymore.

**Comment by ThomasGorisse** [comment]
Awesome video!!!
Very nice app, good job.
Would you mind sharing the video link within the [Discord](https://discord.gg/UbNDDBTNqb) #showcase channel?
Can I use it on the README page?
Tell me if you plane to move to SceneView, we will help on the migrating.

**Comment by ThomasGorisse** [comment]
You can't imagine the pleasure I have to see your vidéo. Everything seems just perfect and your use case is just awesome
