### ISSUE TITLE
Sceneform-Android MAINTAINED IS NOT RENDREING GLB FILES CONTAINING KTX2 TEXTURE

### ISSUE THREAD

**Issue by Tomlp14** [SceneView/sceneform-android#371]
Will sceneform maintained support rendering GLB files containing KTX2 at some point? 
With KTX2     |  Without KTX2 (it's larger)
:-------------------------:|:-------------------------:
 ![Screenshot_20220518-175858_AR glTF](https://user-images.githubusercontent.com/8157591/169180427-2ac882cb-e641-4e72-9563-3dff5f452014.jpg) | ![Screenshot_20220518-175816_AR glTF](https://user-images.githubusercontent.com/8157591/169180519-286e9a10-bfd3-4eb1-b0b0-f041dd89f1a1.jpg)

**Comment by ThomasGorisse** [comment]
Answer here: https://github.com/SceneView/sceneview-android/issues/86
