### ISSUE TITLE
Colors are not correct

### ISSUE THREAD

**Issue by zewillze** [SceneView/sceneform-android#372]
Hi, we have met a problem about the color. 
We get gltf file exported from Blender. 
But when we try to show the model in Sceneform with Android,
we found that the color are not correct.
Would you give us some advise ?
Thanks a lot.
 
<img width="172" alt="WX20220519-233059@2x" src="https://user-images.githubusercontent.com/6038316/169337194-d10bc7b2-4023-4a6d-80bd-ff0fc6a0dfa6.png">
<img width="112" alt="WX20220519-233109@2x" src="https://user-images.githubusercontent.com/6038316/169337231-a26bf989-ce85-4085-a1b3-0c5896d7eec1.png">
)

**Comment by ThomasGorisse** [comment]
What version of Sceneform are you using?

**Comment by zewillze** [comment]
we have used both 1.20.0 and 1.20.4. thanks.

**Comment by zewillze** [comment]
We try to load texture like:
`private Texture loadTexture(String texturePath) {
        Bitmap bitmap;
        try {
            bitmap = BitmapFactory.decodeStream(this.getBaseContext().getAssets().open(texturePath));
        } catch (Exception e) {
            return null;
        }

        Engine engine = EngineInstance.getEngine().getFilamentEngine();
        Texture texture = new Texture.Builder()
                .width(bitmap.getWidth())
                .height(bitmap.getHeight())
                .sampler(Texture.Sampler.SAMPLER_2D)
                .format(Texture.InternalFormat.SRGB8_A8)
                .levels(0xff)
                .build(engine);
        TextureHelper.setBitmap(engine, texture, 0, bitmap);
        texture.generateMipmaps(engine);
        return texture;
    }`

then set to material like:

`Texture texture = loadTexture("chair_fabric_albedo.png");
            TextureSampler textureSampler = new TextureSampler();

            material.setParameter("baseColorMap", texture, textureSampler);
            material.getMaterial().isColorWriteEnabled();`

**Comment by zewillze** [comment]
> See #163

Still not work after trying these codes :(

**Comment by zewillze** [comment]
we are think if it relate to this:
`material.baseColor.rgb = inverseTonemap(material.baseColor.rgb)`
but we can not find a way to set it when we are using gltf file
do you have any idea ?
