### ISSUE TITLE
Issue when rotating 2D views (set on AR Nodes) to face the camera 

### ISSUE THREAD

**Issue by hocesjc** [SceneView/sceneform-android#382]
Hi

https://github.com/google-ar/sceneform-android-sdk/issues/783

this is an issue of the old Sceneform but i have the same issue with this new library

thanks.

**Comment by grassydragon** [comment]
Hi!
Keep in mind that the `ViewRenderable` can look right because of flipping the texture but can be rotated 180 degrees.
See this discussion: https://github.com/SceneView/sceneform-android/discussions/377
