### ISSUE TITLE
Yellowish tone on glb models

### ISSUE THREAD

**Issue by MatHeartGaming** [SceneView/sceneform-android#384]
Hi guys, I've just switched to this newer version of Sceneform and so far I like it, models feels more realistic, but I noticed that the engine gives an unwanted yellowish look to my models. Is there a way to change that from code? Or is it model related? Using older versions of Sceneform didn't seem to have this issue. Have a look at the attached photos i took to have an idea of what I'm talking about. Thanks in advance to anyone who will help!
![Img181aab29a79](https://user-images.githubusercontent.com/25991137/176205514-fba10210-8208-444c-ad9d-8b65c0701660.png)
![Img181aab2c900](https://user-images.githubusercontent.com/25991137/176205519-5eddcd32-c6f1-4827-895c-5d49279679bb.png)
![Img181aab42804](https://user-images.githubusercontent.com/25991137/176205532-e02ef213-a460-4189-aa0d-4ab4634feae5.png)

![Img181aab283a5](https://user-images.githubusercontent.com/25991137/176205469-0a1c62c2-0aa8-4dea-b764-a45f3fbb7ab6.png)
.

**Comment by grassydragon** [comment]
Hi!
You can see this issue: https://github.com/SceneView/sceneform-android/issues/322
The yellow color comes from the default environment.

**Comment by MatHeartGaming** [comment]
> 



> Hi! You can see this issue: #322 The yellow color comes from the default environment.

Thank you!
