### ISSUE TITLE
Model with multiple materials issue

### ISSUE THREAD

**Issue by tapmyads-dev1** [SceneView/sceneform-android#387]
Hello Team,
We are loading single model with multiple materials in it.  We are trying to edit the properties of materials. Currently, we are only able to access the material with the Zero index (0) but unable to access further material indexes . Can any please provide solution for this issue?

Thanks

**Comment by e4basil** [comment]
any solution for this ?

**Comment by SamihMustafa** [comment]
Each renderable node has material instance so could access from there as well. would need to see the gltf to know why you can only access one

**Comment by gauravbiyani033** [comment]
I am doing it using 

```
modelNode?.modelInstance?.materialInstances?.map { materialInstance -> 

    // Here you can do all sort of operations on materialInstance such as change any texture, color, etc.
}
```

Hope it helps
