### ISSUE TITLE
Ignore antialiasing for selected nodes

### ISSUE THREAD

**Issue by 8kdesign** [SceneView/sceneform-android#390]
Hi! 

I would like to check if it is possible to avoid antialiasing for a ViewRenderable as antialiasing blurs the imageview in it. The other nodes would still need to have antialiase though.

By the way, is there anything I can do to achieve the maximum quality for a ViewRenderable?

Thank you.

Kind regards,

Wen Hao

**Comment by grassydragon** [comment]
Hi!
The quality of the `ViewRenderable` depends on the texture resolution. You can achieve better quality by making a `View` larger in the layout and smaller in 3D by using a [`ViewSizer`](https://github.com/SceneView/sceneform-android/blob/ba2c818151b91296f048711f494e1acc239ff809/core/src/main/java/com/google/ar/sceneform/rendering/ViewSizer.java).
