### ISSUE TITLE
achieving occlusion with Augmented faces

### ISSUE THREAD

**Issue by furkandindar** [SceneView/sceneform-android#391]
I am using Augmented faces and rendering objects on the face. I want 1 object to act as an occluder(should be non-visible) so that it can hide some parts of the visible object when you look at it from different angles. in ThreeJS I would simply set occluder material's "colorWrite=false" so the object would still be there acting as an occluder but not visible to the user. I can't access "colorWrite" property on sceneform. Is there any way I can set a material's "colorWrite" to false so it can act as an occluder?

**Comment by weijiaqi** [comment]
Did you solve it, I had this problem too, I put an object as an occluder, but it kept seeing
