### ISSUE TITLE
Lifecycle issues when using lib with Jetpack Compose

### ISSUE THREAD

**Issue by drdlx** [SceneView/sceneform-android#396]
Hi!

I've used your library in my app, and I think I've encountered some kind of an issue? I've added the `ArFromtFacingFragment` from the library into Jetpack Compose function, and it seems that it can't initialize properly in the moment when the other compose ui components are ready, it just displays a black screen when the activity is opened, and I have to redraw the composable in order to see the AR function's result.

I wasn't able to use the library's Kotlin version, cause it's working unstable on my phone, and I wasn't able to load the screen at all, even without jetpack compose.

I'm storing the link to ARFragment in ViewModel as a LiveData object, so it seems that the ARFrontFacing fragment just can't load when the other UI components around it are done? It logs the model's coordinates as it's supposed to, for example, it just doesn't display it on the UI. 

I'm not sure if it's a bug or not, maybe it's something to consider when updating the Kotlin library with jetpack compose support? Maybe I should add something to 'update' scet

I'm using Galaxy Note 9 for tests, if it makes any difference here. 

Let me know if there's some other info that can be useful for the future versions. 

Thanks for your time!

**Comment by drdlx** [comment]
Nvm, I think I found it

**Comment by ThomasGorisse** [comment]
Please share your results here.

For the SceneView (Kotlin) part, can you use the latest main branch version? It introduced some fixes on rendering and might work better.
We have an `AugmentedImageNode` in the private SceneView Extended repo.
I can add you there if you are open on sharing a simple Compose sample usage.

**Comment by drdlx** [comment]
I'm sooooo sorry for a late response. :( 

Here, I've made a very small app that just displays an ARFrontFacingFragment without any kind of models used. https://github.com/drdlx/Compose-Sceneform-Example

There are 2 branches in project, master one works flawlessly on my phone, whilst the other one with the livedata doesn't.

What's more interesting is that instead of posting it via separate function, it's possible to init the AR Fragment fine, but on, let's say, one initializing function from main activity, so if you init the screen and put the fragment in one place, it's working. But try and put it via some sort of async flow, and it's getting a black screen.

Maybe to use it properly, I should attach the initialization to lifecycle events?

Hope I'm making any sense here.

**Comment by ThomasGorisse** [comment]
Hi!
That's perfect, thanks.
One simple question; Why are you using Sceneform instead of SceneView?

**Comment by drdlx** [comment]
@ThomasGorisse I've tried it at first, but on my Galaxy Note 9 it just displayed a black scren in examples. I use Linage OS with Android 12 on it, which might be the reason it's happening.

It just stays like this: [Imgur](https://i.imgur.com/gnET9N5.jpg)

I've had a chance to check the SceneView on Galaxy S20, though, and it works flawlessly there.
