### ISSUE TITLE
About rotation order

### ISSUE THREAD

**Issue by canlang** [SceneView/sceneform-android#397]
https://github.com/SceneView/sceneform-android/blob/ba2c818151b91296f048711f494e1acc239ff809/core/src/main/java/com/google/ar/sceneform/math/Quaternion.java#L388

Hello!
The document said the order of Euler rotation is ZYX, but it seemed like the rotation order is applied with ZXY.
I think the code is rotating Z axis quaternion first, then rotating X axis quaternion, and then Y. 
Am I wrong? 
I appreciate your help

**Comment by grassydragon** [comment]
Hi!
I haven't tested it but looking at the `multiply` method documentation it seems that the order is `XYZ`:
https://github.com/SceneView/sceneform-android/blob/ba2c818151b91296f048711f494e1acc239ff809/core/src/main/java/com/google/ar/sceneform/math/Quaternion.java#L233

**Comment by grassydragon** [comment]
So yes, you are probably right.

**Comment by canlang** [comment]
Thanks for your check!
