### ISSUE TITLE
Is there any way to use arcore geospatial api with sceneform?

### ISSUE THREAD

**Issue by twoone17** [SceneView/sceneform-android#398]
Hi, i'm having hard time using newly released geospatial api in arcore with sceneform.
I tried to combine it, arcore is using geospatial api with session,

[](https://developers.google.com/ar/develop/java/geospatial/developer-guide)

Earth earth = session.getEarth();
if (earth != null && earth.getTrackingState() == TrackingState.TRACKING) {
 GeospatialPose cameraGeospatialPose = earth.getCameraGeospatialPose();
}

But sceneform is not using session directly, views are different(arfragment and glsurface) and also the way they processes are so different(if my understanding is right)..
So I can't figure out the way.

Is there any way to use arcore geospatial api with sceneform?
I aimed to get the geospatial information like latitude, altitude in my sceneform project.(I imported the sample-ar-model-viewer-java)
Please help me.. ㅠㅠ

**Comment by yhishi** [comment]
@twoone17 
I don't think this `sceneform-android` supports geospatial api, 
please check [sceneview-android](https://github.com/SceneView/sceneview-android#ar-geospatial-api).

I'm trying too, but can't get it to work.:sweat_smile:
https://github.com/SceneView/sceneview-android/issues/141
