### ISSUE TITLE
How to hide the white part and only keep the door that the ring enters?

### ISSUE THREAD

**Issue by weijiaqi** [SceneView/sceneform-android#404]
![微信图片_20220812111822](https://user-images.githubusercontent.com/16206185/184279113-f265071a-8d49-40f4-9f21-402b642da236.png)

**Comment by weijiaqi** [comment]
Only the entrance is kept, and the white part is hidden. How to do it?

**Comment by grassydragon** [comment]
Hi!
It isn't a simple question. You should experiment with occlusion materials and rendering priority if you want the white shell to be invisible but hide objects inside it.

**Comment by weijiaqi** [comment]
AnchorNode anchorNode = new AnchorNode();
      
        Vector3 point = new Vector3(0, 0, -2);
        anchorNode.setWorldPosition(point);
        anchorNode.setParent(arFragment.getArSceneView().getScene());

        TransformableNode andy = new TransformableNode(transformationSystem);
        andy.setParent(anchorNode);
        andy.setRenderable(this.model4).animate(true).start();
        andy.setWorldScale(new Vector3(5f, 5f, 5f));
        andy.setLocalPosition(new Vector3(0f, 2f, -7f));
        andy.setLocalRotation(Quaternion.axisAngle(new Vector3(0f, 1f, 0f), 180f));

      
        andy.getScaleController().setEnabled(false);
  
     //   andy.getRotationController().setEnabled(false);

        //model4 is the inner object model3 is the white mask
        Node node = new Node();
        node.setParent(andy);
        node.setRenderable(this.model3).animate(true).start();

**Comment by weijiaqi** [comment]
Is it correct to write the rendering priority like this?

**Comment by weijiaqi** [comment]
https://download.redph.cn/meta/ar/q1.glb
https://download.redph.cn/meta/ar/q2.glb
With these two models it is not possible to achieve a white shell that is invisible but hides the objects inside it，Can you help me see if I'm missing any steps?

**Comment by weijiaqi** [comment]
ModelRenderable.builder()
                .setSource(this, Uri.parse("models/baike1.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    MainActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model3 = model;
                        activity.model3.setRenderPriority(Renderable.RENDER_PRIORITY_LAST);
                        activity.model3.setShadowCaster(true);
                        activity.model3.setShadowReceiver(true);
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });


        ModelRenderable.builder()
                .setSource(this, Uri.parse("models/tiankongdimian1.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    MainActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model4 = model;
                        activity.model4.setRenderPriority(0);
                        activity.model4.setShadowCaster(true);
                        activity.model4.setShadowReceiver(true);
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });

**Comment by weijiaqi** [comment]
ModelRenderable.builder()
                .setSource(this, Uri.parse("models/baike1.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    MainActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model3 = model;
                        activity.model3.setRenderPriority(Renderable.RENDER_PRIORITY_LAST);
                        activity.model3.setShadowCaster(true);
                        activity.model3.setShadowReceiver(true);
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });


        ModelRenderable.builder()
                .setSource(this, Uri.parse("models/tiankongdimian1.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    MainActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model4 = model;
                        activity.model4.setRenderPriority(0);
                        activity.model4.setShadowCaster(true);
                        activity.model4.setShadowReceiver(true);
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });

**Comment by weijiaqi** [comment]
hi, please reply when you see it, I'm stuck here, I have been unable to make the outermost white mask transparent, and only keep one incoming AR Portal

**Comment by weijiaqi** [comment]
The effect I want to achieve is ar portal, but I have been unable to make the white mask transparent

**Comment by weijiaqi** [comment]
hi, brother, please reply when you see it, give me some ideas to solve it

**Comment by grassydragon** [comment]
See how this is done for augmented faces: https://github.com/SceneView/sceneform-android/blob/master/ux/src/main/java/com/google/ar/sceneform/ux/AugmentedFaceNode.java#L243
I'm not sure if it is possible to achieve in glTF.

**Comment by weijiaqi** [comment]
When did you write a demo of an ar portal? There is very little Android-related information on git.

**Comment by grassydragon** [comment]
I haven't. It is just a similar functionality of hiding other objects with an invisible face mesh :sweat_smile:

**Comment by weijiaqi** [comment]
@grassydragon  I exited and entered multiple times in my class, and then a black screen appeared in the interface rendering, but the click event of the model still existed. I checked all the related problems and couldn't solve it. How can I avoid this situation, I How to write it in the onDestroy method

**Comment by weijiaqi** [comment]
@grassydragon I exited and entered multiple times in my class, and then a black screen appeared in the interface rendering, but the click event of the model still existed. I checked all the related problems and could not solve it. How can I avoid this situation? How to write it in the onDestroy method

**Comment by grassydragon** [comment]
I actually haven't used any special code in the `onDestroy` method and haven't encountered this problem.

**Comment by weijiaqi** [comment]
On the Samsung Note10, I first entered the class class to render the model, and the screen went black when I exited and then entered. How do I destroy the previously rendered ones?

**Comment by weijiaqi** [comment]
Is the model too complicated?

**Comment by grassydragon** [comment]
Are you using a fragment or an activity for the AR screen?

**Comment by weijiaqi** [comment]
fragment

**Comment by grassydragon** [comment]
This can cause some problems if the fragment isn't destroyed. You can try using an activity.

**Comment by weijiaqi** [comment]
ok, thanks

**Comment by weijiaqi** [comment]
I tried to modify it, and I changed it to the same as the ar-model-viewer-java provided in the demo, but there will still be a black screen after exiting and re-entering

**Comment by weijiaqi** [comment]
https://download.redph.cn/meta/ar/shijie1.glb

**Comment by weijiaqi** [comment]
This is my model, will it have something to do with the material of the model?

**Comment by grassydragon** [comment]
> I tried to modify it, and I changed it to the same as the ar-model-viewer-java provided in the demo, but there will still be a black screen after exiting and re-entering

If you see the same behavior when you replace the model in the sample application, it can be a problem with the model, yes.

**Comment by weijiaqi** [comment]
How can I turn off the ambient light, when I go to view the model at night, it is dark

**Comment by weijiaqi** [comment]
ArSceneViewKt.setLightEstimationConfig(this.arSceneView, LightEstimationConfig.DISABLED);

**Comment by weijiaqi** [comment]
After I turned it off, the model started to turn yellow

**Comment by weijiaqi** [comment]
this.arSceneView.setFrameRateFactor(SceneView.FrameRate.FULL);
        ArSceneViewKt.setLightEstimationConfig(arSceneView, LightEstimationConfig.DISABLED);
        HDREnvironmentKt.loadEnvironmentAsync(
                              HDRLoader.INSTANCE,
                                this,
                                "environments/studio_small_09_2k.hdr",
                                false,
                               LifecycleOwnerKt.getLifecycleScope(this),
                                hdrEnvironment -> {
                                        float indirectLightIntensity = SceneViewKt.getEnvironment(arSceneView).getIndirectLight().getIntensity();
                                       SceneViewKt.setEnvironment(arSceneView, new Environment(hdrEnvironment.getSphericalHarmonics(), hdrEnvironment.getIndirectLight(), null));
                                       SceneViewKt.getEnvironment(arSceneView).getIndirectLight().setIntensity(indirectLightIntensity);
                                        return Unit.INSTANCE;
                                   }
                                );

**Comment by weijiaqi** [comment]
I saw this part of the code you wrote, and I still have a problem after adding it

**Comment by weijiaqi** [comment]
After adding the effect
![11](https://user-images.githubusercontent.com/16206185/186311451-e2e121d1-4b89-43c6-910f-2c97908c915f.jpg)

**Comment by weijiaqi** [comment]
the effect i want
![222](https://user-images.githubusercontent.com/16206185/186311495-5a24b7aa-90b2-447b-8cac-fcc061fda036.jpg)

**Comment by grassydragon** [comment]
> After I turned it off, the model started to turn yellow

It comes from the default HDR environment.

> I saw this part of the code you wrote, and I still have a problem after adding it

Rendering the occlusion shell shouldn't affect the materials of other objects.

**Comment by grassydragon** [comment]
Take a look at this issue: https://github.com/SceneView/sceneform-android/issues/322
I don't remember if it is actually possible to set the ambient light to a color instead of an HDR texture.

**Comment by ThomasGorisse** [comment]
You have to set the `sceneView.environment.indirectLight` to the same .hdr that was used inside your model.

**Comment by ThomasGorisse** [comment]
But anyway, this is more a not exported gltf texture issue.

**Comment by weijiaqi** [comment]
hi, my model doesn't use hdr textures, I use jpg or png, how can I avoid yellowing?@ThomasGorisse

**Comment by grassydragon** [comment]
> hi, my model doesn't use hdr textures, I use jpg or png, how can I avoid yellowing?@ThomasGorisse

Hi!
Maybe not inside your model but in the 3D modeling program that was used for creating and previewing the model.

**Comment by weijiaqi** [comment]
I found that the modeling program uses softUmbrella.hdr, but after I added it, the program could not run and crashed directly

**Comment by weijiaqi** [comment]
![微信图片_20220825162007](https://user-images.githubusercontent.com/16206185/186613849-fd093254-5b3a-47ef-8de4-a6e1c0b26465.png)

**Comment by weijiaqi** [comment]
![2222](https://user-images.githubusercontent.com/16206185/186800021-ee7ee9ce-572b-43eb-b897-0b255d1fc4be.png)

**Comment by weijiaqi** [comment]
This is all the hdr in the modeling program, I tried each of them individually, but still didn't show the desired effect

**Comment by weijiaqi** [comment]
The problem of the black screen still exists. The following situation occurs on some Xiaomi phones and Samsung phones. I have not found a good solution. When I kill the app from the background and enter again, it is normal. I am exiting the current Do I need to do anything related to the class?

**Comment by weijiaqi** [comment]
I have hidden the cloud aiming point, which is directly presented by opening the current activity. I will send you the relevant code. Please help me to see

**Comment by weijiaqi** [comment]
This is the code for the layout

    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/arFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

**Comment by weijiaqi** [comment]
Below is the activity
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (savedInstanceState == null) {
            if (Sceneform.isSupported(this)) {
                getSupportFragmentManager().beginTransaction()
                        .add(R.id.arFragment, CleanArFragment.class, null)
                        .commit();
            }
        }
        loadModels();
    }

    public void loadModels() {
        WeakReference<ArCenterConsoleActivity> weakActivity = new WeakReference<>(this);
        ModelRenderable.builder()
                .setSource(this, Uri.parse("models/shijieqiu.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build()
                .thenAccept(model -> {
                    ArCenterConsoleActivity activity = weakActivity.get();
                    if (activity != null) {
                        activity.model = model;
                    }
                })
                .exceptionally(throwable -> {
                    Toast.makeText(
                            this, "Unable to load model", Toast.LENGTH_LONG).show();
                    return null;
                });
          handlerModel = new Handler();
        handlerModel.postDelayed(mAdModel, 1000);
}

 Runnable mAdModel = () -> showObj();

private void showObj() {
        anchorNode = new AnchorNode();
        anchorNode.setParent(arFragment.getArSceneView().getScene());

        andy = new TransformableNode(transformationSystem);
        andy.setParent(anchorNode);
        andy.setRenderable(this.model).animate(true).start();
        andy.setWorldScale(new Vector3(0.3f, 0.3f, 0.3f));
        andy.setLocalPosition(new Vector3(0f, 3.7f, -10.5f));
        andy.getRenderableInstance().setCulling(false);
        andy.getScaleController().setEnabled(false);
        andy.getRotationController().setEnabled(false);
        andy.getTranslationController().setEnabled(false);
        andy.select();
}

**Comment by grassydragon** [comment]
Hi!
While it isn't probably related to the issue with a black screen, I suggest not to use a timeout (`handlerModel.postDelayed(mAdModel, 1000);`) but to show the model in `thenAccept`.

**Comment by grassydragon** [comment]
Other than that Xiaomi and Samsung can modify Android more than other brands. Is the activity destroyed when going back from it?

**Comment by weijiaqi** [comment]
Ok thanks, I removed the handler and the phone started to get hot when loading multiple models. Is there a solution to this?

**Comment by grassydragon** [comment]
I don't think these things are related to each other.

**Comment by weijiaqi** [comment]
Hi, I have tried multiple models of phones to load glb models with animations. I stay on the interface for a long time, and there will be problems of freezing and phone heating. Is it because the model is too complicated?
If it is because of the problem of the model, is there anything to pay attention to when making the model, is there any size limit for the model, and what are the requirements for texture? Please help to answer

**Comment by grassydragon** [comment]
Hi!
If the model doesn't impact performance at first but the device starts heating with time, it can be related to not very efficient heat dissipation or some memory leaks happening. I would suggest to experiment with different models to see whether the complexity of the model is the main cause of overheating.

**Comment by weijiaqi** [comment]
![微信图片_20220909171717](https://user-images.githubusercontent.com/16206185/189316488-41f5898f-d47e-4d0a-bcbb-e8f6cc4a8035.png)

**Comment by weijiaqi** [comment]
I opened Profiler and found that MEMORY will not destroy the cache when closing the current class. I repeatedly exited and entered again. The maximum MEMORY reached 8GB. This is the reason why the phone is hot. How can I avoid it?

**Comment by grassydragon** [comment]
You need to find what causes the memory leak.

**Comment by weijiaqi** [comment]
model = ModelRenderable
                .builder()
                .setSource(this
                        , Uri.parse("models/quiworld.glb"))
                .setIsFilamentGltf(true)
                .setAsyncLoadEnabled(true)
                .build();

**Comment by weijiaqi** [comment]
CompletableFuture.allOf(model)
                .handle((ok, ex) -> {
                    try {
                        FootprintSelectionVisualizer selectionVisualizer = new FootprintSelectionVisualizer();
                        transformationSystem = new TransformationSystem(getResources().getDisplayMetrics(), selectionVisualizer);
                        arFragment.getArSceneView().getScene().addOnPeekTouchListener((hitTestResult, motionEvent) -> {
                            transformationSystem.onTouch(hitTestResult, motionEvent);
                        });
                        anchorNode = new AnchorNode();
                        anchorNode.setParent(arFragment.getArSceneView().getScene());


                        andy = new TransformableNode(transformationSystem);
                        andy.setParent(anchorNode);
                        andy.setRenderable(model.get()).animate(true).start();
                        andy.setWorldScale(new Vector3(0.3f, 0.3f, 0.3f));
                        andy.setWorldPosition(new Vector3(0f, 0f, 0.5f));
                        andy.getRenderableInstance().setCulling(false);
                        // 禁止缩放
                        andy.getScaleController().setEnabled(false);
                        andy.getRotationController().setEnabled(false);
                        andy.getTranslationController().setEnabled(false);
                        andy.select();


                    } catch (ExecutionException e) {
                        e.printStackTrace();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    return null;
                });

**Comment by weijiaqi** [comment]
I didn't write anything except this, because of the memory leak?

**Comment by weijiaqi** [comment]
Just the above code and nothing else

**Comment by weijiaqi** [comment]
https://download.redph.cn/meta/ar/quiworld.glb  This is the glb model

**Comment by weijiaqi** [comment]
I repeatedly enter and exit MEMORY to reach 8GB

**Comment by weijiaqi** [comment]
See it, please tell me how to solve it, hard work

**Comment by weijiaqi** [comment]
hi, did you see the problem and open my glb link, if you see it, please reply and see what caused the problem
