### ISSUE TITLE
Glb model flip in x axis , Need Help!!!

### ISSUE THREAD

**Issue by dandingol03** [SceneView/sceneform-android#406]
**Context:**
Hi @ThomasGorisse , i use `sceneform-android` to load glb model. However, it seems like the model uv become flip in x axis. You can see the `rich` text mesh flip obviously. By the way, i downgrade the filament version to 1.12.5. I need help!!! Thanks in advance~

the render result:
![image](https://user-images.githubusercontent.com/13013579/184656586-4711eb53-28e0-411d-8e25-9364b2bf8877.png)

the origin image:
![image](https://user-images.githubusercontent.com/13013579/184660772-d515060f-4456-4125-acc0-a3f07c6c21fe.png)

**Comment by grassydragon** [comment]
Hi!
This is an intended behavior for Augmented Faces since the scene is rendered as if you look in a mirror.

**Comment by grassydragon** [comment]
By the way, the same is true for your t-shirt :sweat_smile:
