### ISSUE TITLE
Rotate model in Sceneview not arcore

### ISSUE THREAD

**Issue by thanhphong190** [SceneView/sceneform-android#412]
hi @ThomasGorisse @grassydragon How to rotate model 3d when load in sceneview not arcore in library? (I very need)

**Comment by grassydragon** [comment]
Hi!
In the 3D only mode the camera should be rotated by default around the model.

**Comment by thanhphong190** [comment]
> Hi! In the 3D only mode the camera should be rotated by default around the model.

hi @grassydragon i use TransformableNode but crash : java.lang.ClassCastException: com.google.ar.sceneform.SceneView cannot be cast to com.google.ar.sceneform.ArSceneView

**Comment by grassydragon** [comment]
> hi @grassydragon i use TransformableNode but crash : java.lang.ClassCastException: com.google.ar.sceneform.SceneView cannot be cast to com.google.ar.sceneform.ArSceneView

I'm sorry I haven't noticed that this is Sceneform and not Sceneview. The `TransformableNode` works only in AR.
