### ISSUE TITLE
CAMERA_UNAVAILABLE on Samsung A23: black screen.

### ISSUE THREAD

**Issue by ironmanromeo** [SceneView/sceneform-android#425]
Hello everybody. This is not a strictly SceneForm-related issue but indirectly it is. It is not clear if it was SceneForm that caused it or it is a problem with the phone: it happens that on a newly purchased **Samsung A23** the camera no longer has the privileges and does not start. The error obtained from a native HelloWorld Java ArCore app returns that the camera is in use by another application. There is no need to close all the apps, delete them, re-install them: nothing is done. I also downloaded the demo app https://play.google.com/store/apps/details?id=com.gorisse.thomas.ar.environmentlights on the phone which has the same problem: the screen stays black. Access to the room has been given to all apps. The system camera app was restarted and I reset the settings: nothing to do. I don't know how it happened but on one occasion the camera unlocked and the apps worked, but once closed and reopened they no longer worked. Looking online "it seems" that the problem is limited to only some Samsung phones, even the A23 is not mentioned because it is still new. Tips? Thanks in advance.

https://developers.google.com/ar/reference/java/com/google/ar/core/TrackingFailureReason

> Motion tracking paused because the camera is in use by another application. Tracking will resume once this app regains priority, or once all apps with higher priority have stopped using the camera. Prior to ARCore SDK 1.13, [NONE](https://developers.google.com/ar/reference/java/com/google/ar/core/TrackingFailureReason#NONE) is returned in this case instead.

**Comment by ThomasGorisse** [comment]
Hi.
Please create an issue on the [ARCore repo](https://github.com/google-ar/arcore-android-sdk) so they make a configuration push for this phone.

**Comment by ironmanromeo** [comment]
Ok. Thx
