### ISSUE TITLE
 incompatible Fragment type

### ISSUE THREAD

**Issue by gabrielegalimbertiphd** [SceneView/sceneform-android#436]
Hi,

I Have this error. How can I change the code?

error: incompatible types: Fragment cannot be converted to ArFragment

arFragment = (ArFragment) fragmentManager.findFragmentById(R.id.fragment);

**Comment by Blizl** [comment]
Does your XML look like this? 


```
<androidx.fragment.app.FragmentContainerView
    android:id="@+id/arFragment"
    android:name="com.google.ar.sceneform.ux.ArFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```
